Updated the example TestStand sequence to make it simpler
ni/measurementlink-labview pull request #197
Opened 2023-04-18 10:59 UTC by Tharun-Sundar

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Updates the TestStand sequence in the DC-Power example measurement to make it simpler by moving the process setup and process cleanup steps to the main sequence.

### Why should this Pull Request be merged?

Based on the feedback discussed in this [Teams post](https://teams.microsoft.com/l/message/19:36f0e963feb84c0c8122e6ddfbe7df7b@thread.tacv2/1676494204834?tenantId=87ba1f9a-44cd-43a6-b008-6fdb45a5204e&groupId=a092c504-be1c-4d21-9ef4-068a40ca6974&parentMessageId=1676494204834&teamName=MeasurementLink%20%26%20ETW%20Global%20Collaboration&channelName=Roadmap%20Input%20and%20Feature%20Ideas&createdTime=1676494204834&allowXTenantAccess=false), moving the process setup and process cleanup steps to the main sequence will simplify the example sequence as the user will only need to run the main sequence to get the expected result. Though this sequence is not efficient for multi-site use case, this change is encouraged as the example sequence is expected to be tailored to users who are beginners in TestStand.

### What testing has been done?

Manually executed the TestStand example sequence with a simulated DC-Power instrument and verified the result.

2023-04-18 18:33 UTC, dixonjoel approved these changes

2023-04-18 19:07 UTC, jarnoldNI commented
Looks good to me.

2023-04-18 19:30 UTC, pbirkhol-ni approved these changes

2023-04-18 23:43 UTC, bkeryan commented
How are we going to document that the examples do setup/cleanup in the main sequence for simplicity and that ProcessSetup/Cleanup is better for use cases such as "Test UUTs" and batch process model?

In addition to whatever content will be updated in the MeasurementLink user manual, I think it would make sense to add a note to the example's README.md: https://github.com/ni/measurementlink-labview/blob/main/Source/Example%20Measurements/NI-DCPower%20Source%20DC%20Voltage/README.md

2023-04-19 14:54 UTC, jarnoldNI commented
> How are we going to document that the examples do setup/cleanup in the main sequence for simplicity and that ProcessSetup/Cleanup is better for use cases such as "Test UUTs" and batch process model?
> 
> In addition to whatever content will be updated in the MeasurementLink user manual, I think it would make sense to add a note to the example's README.md: https://github.com/ni/measurementlink-labview/blob/main/Source/Example%20Measurements/NI-DCPower%20Source%20DC%20Voltage/README.md

I always like the idea of documenting it. Long term, I think the best way is that there will be a specific multisite example which addresses this along with all the other considerations for multisite testing.

2023-04-19 18:00 UTC, bkeryan commented
> > How are we going to document that the examples do setup/cleanup in the main sequence for simplicity and that ProcessSetup/Cleanup is better for use cases such as "Test UUTs" and batch process model?
> > In addition to whatever content will be updated in the MeasurementLink user manual, I think it would make sense to add a note to the example's README.md: https://github.com/ni/measurementlink-labview/blob/main/Source/Example%20Measurements/NI-DCPower%20Source%20DC%20Voltage/README.md
> 
> I always like the idea of documenting it. Long term, I think the best way is that there will be a specific multisite example which addresses this along with all the other considerations for multisite testing.

Okay, I created [AB#2371166](https://dev.azure.com/ni/DevCentral/_workitems/edit/2371166) about this.

2023-04-19 18:59 UTC, Tharun-Sundar commented
@pbirkhol-ni @bkeryan @jarnoldNI The sequence has been updated to merge the 3 steps in the Setup section, that handles pin map registration, into a single LabVIEW action step. This simplifies the sequence further such that there are 2 steps each in the Setup and Cleanup sections, one for pinmap and one for sessions. Please share your comments.

2023-04-19 21:43 UTC, bkeryan commented
> @pbirkhol-ni @dixonjoel @bkeryan @jarnoldNI The sequence has been updated to merge the 3 steps in the Setup section, that handles pin map registration, into a single LabVIEW action step. This simplifies the sequence further such that there are 2 steps each in the Setup and Cleanup sections, one for pinmap and one for sessions. Please share your comments.

Here's our original thread about how to look up the file path (in Python): https://github.com/ni/measurementlink-python/pull/134#discussion_r1037651109

We discussed whether to do it in TestStand or in the code module. We chose to do it in TestStand because it was easier, not because there were any strong reasons not to do it in the code module. 

So I think moving the path lookup to the code module is fine. However, we want it to use TestStand's FindFile function, so that users can locate the file in another directory that is in TestStand's search path.

2023-04-20 11:09 UTC, Tharun-Sundar commented
> > @pbirkhol-ni @dixonjoel @bkeryan @jarnoldNI The sequence has been updated to merge the 3 steps in the Setup section, that handles pin map registration, into a single LabVIEW action step. This simplifies the sequence further such that there are 2 steps each in the Setup and Cleanup sections, one for pinmap and one for sessions. Please share your comments.
> 
> Here's our original thread about how to look up the file path (in Python): [ni/measurementlink-python#134 (comment)](https://github.com/ni/measurementlink-python/pull/134#discussion_r1037651109)
> 
> We discussed whether to do it in TestStand or in the code module. We chose to do it in TestStand because it was easier, not because there were any strong reasons not to do it in the code module.
> 
> So I think moving the path lookup to the code module is fine.
> 
> However, we want it to use TestStand's `FindFile` function, so that users can locate the file in another directory that is in TestStand's search path. I think this is it: ![image](https://user-images.githubusercontent.com/17914399/233207205-1efa9211-f573-483c-884e-46227abe2032.png)

Updated the Get Pin Map Path VI as suggested

2023-04-20 13:57 UTC, bkeryan requested changes

2023-04-20 13:57 UTC, bkeryan commented on Source/Example Measurements/NI-DCPower Source DC Voltage/NI-DCPower Measurement/TestStand Code Modules/Update Pin Map.vi
Discussed in our conference call today:
- `Get Pin Map Path.vi` modifies the PinMapPath variable in TestStand which is an unexpected side effect for a "get" VI
- The PinMapPath variable is a file global, so modifying it creates a dirty dot
- Register & Create Sessions really wants the PinMapId, not the PinMapPath, so we don't need to pass the path back to TestStand
- We can probably merge PinMapFileName and PinMapPath, assuming that passing an absolute path to FindFileEx returns the original path unchanged.
- For code modules that need the PinMapPath for other things, like NI-Digital, it may make sense to add a separate step rather than do that stuff in Register & Create Sessions

2023-04-21 06:47 UTC, Tharun-Sundar commented on Source/Example Measurements/NI-DCPower Source DC Voltage/README.md
> +  - For the sake of simplicity, the TestStand sequence handles pin map and session registration and unregistration in the Setup and Cleanup sections of the main sequence. For "Test UUTs" and batch pr
> "Setup", "ProcessSetup", etc. are programmatic identifiers so use monospace and match the spacing used in the product.
> 
> "Test UUTs" is a menu item, so use bold.
> 
> "Callbacks" is not part of an identifier or proper noun. Use lowercase.

Updated the ReadMe as per suggestion.

2023-04-21 07:31 UTC, Tharun-Sundar commented on Source/Example Measurements/NI-DCPower Source DC Voltage/NI-DCPower Measurement/TestStand Code Modules/Update Pin Map.vi
Changes made based on the conference call discussion:
- Removed `Pin Map File Name` file global and modified the validation of `Pin Map Path` file global so that user can provide both relative and absolute paths.
- Added `Locals.PinMapId` to store Pin Map ID and use it for registering sessions.

Regarding the discussion points:
- `Get Pin Map Path.vi` modifies the PinMapPath variable in TestStand which is an unexpected side effect for a "get" VI.
  - The PinMapPath variable is not updated with the absolute path. Instead, the pin map ID is stored in `Locala.PinMapId` and used for registering sessions.
- The PinMapPath variable is a file global, so modifying it creates a dirty dot. Sequence execution shouldn't do that.
  - PinMapPath variable is not modified by the 'Get Pin Map Path.vi`.
- Register & Create Sessions really wants the PinMapId, not the PinMapPath, so we don't need to pass the path back to TestStand.
  - Stored the pin map ID in `Locals.PinMapId` and passed it to the `Create and Register Sessions.vi`.
- We can probably merge PinMapFileName and PinMapPath, assuming that passing an absolute path to FindFileEx returns the original path unchanged.
  - Removed PinMapFileName. Using FindFileEx to find the absolute pin map path if the value in PinMapPath variable is relative.
- For code modules that need the PinMapPath for other things, like NI-Digital, it may make sense to add a separate step rather than do that stuff in Register & Create Sessions.
  - Will handle this in the example TestStand sequence of the NI-Digital python measurement.

2023-04-25 13:55 UTC, bkeryan requested changes

2023-04-25 13:55 UTC, bkeryan commented on Source/Example Measurements/NI-DCPower Source DC Voltage/NI-DCPower Measurement/TestStand Code Modules/Update Pin Map.vi
I like how this code module returns the pin map id and the step uses it to set `Locals.PinMapId`. I think that is more transparent than setting TestStand variables from the code module.
![image](https://user-images.githubusercontent.com/17914399/234294114-f3460c38-d6b5-4941-8f57-306955faadeb.png)

We are setting the temporary global from the code module. Is it possible for TestStand steps to get/set the temporary global like any other TestStand variable? If so, we could remove `Locals.PinMapId` and use the temporary global instead. However, I cannot see how to do that.

If it's not possible to get/set temporary globals like any other TestStand variable, then the current approach is fine.

2023-04-25 13:55 UTC, bkeryan commented on Source/Example Measurements/NI-DCPower Source DC Voltage/NI-DCPower Measurement/TestStand Code Modules/Update Pin Map.vi
Style: resize block diagrams to an appropriate size, not full screen.

This applies to all of the VIs.

2023-04-25 13:55 UTC, bkeryan commented on Source/Example Measurements/NI-DCPower Source DC Voltage/NI-DCPower Measurement/TestStand Code Modules/subVIs/Get Pin Map Path.vi
You need to tell `FileFileEx` where the current sequence file is.
![image](https://user-images.githubusercontent.com/17914399/234299056-ae1b4ea1-07ea-456e-b8d2-4f676d559edd.png)

https://www.ni.com/docs/en-US/bundle/teststand/page/tsapiref/reftopics/engine_findfileex_m.htm

> searchContext As [Variant](https://www.ni.com/docs/en-US/bundle/teststand/page/tsapiref/reftopics/datatypes.htm)
>
> [In] [[Optional](https://www.ni.com/docs/en-US/bundle/teststand/page/tsapiref/infotopics/optional_parameters.htm)] Contains the directory of the sequence file, which may also be searched for relative paths. This argument may be empty.

2023-04-25 14:12 UTC, bkeryan commented on Source/Example Measurements/NI-DCPower Source DC Voltage/NI-DCPower Measurement/TestStand Code Modules/subVIs/Get Pin Map Path.vi
FYI, I think you can pass the SequenceFile refnum for the searchContext parameter.

2023-04-25 18:01 UTC, bkeryan requested changes

2023-04-25 18:01 UTC, bkeryan commented on Source/Example Measurements/NI-DCPower Source DC Voltage/NI-DCPower Measurement/TestStand Code Modules/subVIs/Get Pin Map Path.vi
I realized when reviewing the Python version that the input to this VI is already a relative or absolute path, so a better naming scheme is to call the parameter "Pin Map Path" and call the VI "Resolve Pin Map Path"

2023-04-26 06:41 UTC, Tharun-Sundar commented on Source/Example Measurements/NI-DCPower Source DC Voltage/NI-DCPower Measurement/TestStand Code Modules/subVIs/Get Pin Map Path.vi
Updated the parameter name to "Pin Map Path" and the VI name to "Resolve Pin Map Path".

2023-04-26 06:43 UTC, Tharun-Sundar commented on Source/Example Measurements/NI-DCPower Source DC Voltage/NI-DCPower Measurement/TestStand Code Modules/subVIs/Get Pin Map Path.vi
Updated the `FindFileEx` method call to take the SequenceFile refnum as searchContext. With this change, the logic is able to find the pin map file in the current sequence file directory.

2023-04-26 06:43 UTC, Tharun-Sundar commented on Source/Example Measurements/NI-DCPower Source DC Voltage/NI-DCPower Measurement/TestStand Code Modules/Update Pin Map.vi
Updated the block diagram size of the VIs appropriately.

2023-04-26 06:43 UTC, Tharun-Sundar commented on Source/Example Measurements/NI-DCPower Source DC Voltage/NI-DCPower Measurement/TestStand Code Modules/subVIs/Set Pin Map ID.vi
Added the label as suggested

2023-04-26 06:45 UTC, Tharun-Sundar commented on Source/Example Measurements/NI-DCPower Source DC Voltage/NI-DCPower Measurement/TestStand Code Modules/Update Pin Map.vi
Removed the 'Check if File or Folder Exists.vi` as the `FindFileEx` method can accept both relative and absolute file paths as input.

2023-04-26 07:34 UTC, Tharun-Sundar commented on Source/Example Measurements/NI-DCPower Source DC Voltage/NI-DCPower Measurement/TestStand Code Modules/Update Pin Map.vi
It is not possible to access TemporaryGlobals in the step. TemporaryGlobals are mainly used internally as their purpose is to maintain internal values that the user doesn't need to know.
I have updated the `Create and Register Sessions.vi` to take the pin map ID from the TemporaryGlobal instead of passing it from `Locals.PinMapId`. With this change, there is no need for `Locals.PinMapId` and it has been removed.

2023-04-26 14:35 UTC, dixonjoel approved these changes

2023-04-27 13:44 UTC, bkeryan approved these changes

2023-04-27 13:47 UTC, merged