[RFC] Add Measurement Service Helpers to the measurement template.
ni/measurementlink-labview pull request #229
Opened 2023-06-27 12:27 UTC by subash-suresh

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md).

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This PR helps distribute the measurement service helper library along with the newly created measurement libraries.

In this PR the following has been done,
- A new measurement library has been created and has been placed in the measurement template folder. This library contains all the instrument-agnostic helper VIs including the session management related helper VIs.
![image](https://github.com/ni/measurementlink-labview/assets/98541596/99abf0b6-5312-4a00-9329-d463b55f9166)

- The logic on adding a library to a project has been taken from `Save As Measurement Service template.vi` and put in a new VI called `add library to project.vi` and the before-mentioned VI has been updated to use this.
  -  `add library to project.vi`
  ![image](https://github.com/ni/measurementlink-labview/assets/98541596/3b3ca6e8-df0f-4078-b058-eb79a2ec5299)
  - `Save As Measurement Service template.vi`
  ![image](https://github.com/ni/measurementlink-labview/assets/98541596/3b8c4474-1d41-49cf-8eb8-a8c1b7bbf048)

- Renamed the `Get Measurement Library.vi` to `Get Library.vi`, since this VI could be used to get any library reference from a project. I have also updated the controls and indicator names accordingly. The VIs using this VI has also been updated.
- Add a new VI to add helper library to the project. This VI checks if the helper library is already present and if yes it skips adding the helper library.
![image](https://github.com/ni/measurementlink-labview/assets/98541596/5c471d1b-fc9b-42d6-beca-d182cdf639bd)
![image](https://github.com/ni/measurementlink-labview/assets/98541596/31cb85bd-95c8-4d74-b822-3c328631cb64)
- Updated the `Create Measurement Service.vi` to add the helper libraries when generating the measurement service.
![image](https://github.com/ni/measurementlink-labview/assets/98541596/ffb22fb8-d17e-4a4a-82e5-426b314d5349)

### Why should this Pull Request be merged?

This PR should be merged to include the common helpers when a new measurement is generated.

### What testing has been done?

- Manually generated 
  - a new measurement service in a blank project.
  - a new measurement when the project already had a helper and another project library present.
- Manually added the library from one project to another, to test the use case of users who might wish to use these helpers in their older projects.

2023-06-27 12:56 UTC, subash-suresh commented
I will remove the RFC tag once we decide if the placement of the library when creating the template.
Currently the placement is outside the project library, another idea is to have it as a nested library inside the measurement library.

I would like to hear some comments on this, hence i am specifically bringing this up.

2023-06-27 16:39 UTC, pbirkhol-ni approved these changes
Overall, I think this is fine. I do want @rfriedma to look at it, though. I have one comment:
- I like the idea of having the helpers library contained within the measurement library. It may not be efficient, but it will definitely avoid linking hell when creating a new measurement. The alternative is to make sure multiple measurements in a project reference the same library. This is probably the best long term solution.

2023-06-27 16:54 UTC, dixonjoel approved these changes
Like I said in the other PR
> Before we add this to the template, I'd like to have more consideration of whether we want the library to be nested, multiple services in a project scenarios, and discuss what happens when we want to change / update the helper library or VIs.

I don't think we need to put this PR in before the release of the repo associated with MeasurementLink 23Q3. We can discuss more and put it in another preview release after that.

2023-06-27 16:54 UTC, dixonjoel commented on Source/Generator/MeasurementLink Measurement Template/Measurement Service Helpers/Measurement Service Helpers.lvlib
Wouldn't we want to add this to the Measurement Template project? As far as I can tell, it's only on disk right now.

2023-06-27 16:54 UTC, dixonjoel commented on Source/Generator/_Editor/Add Library To Project.vi
What happens when you add a second measurement service to the project? Does it overwrite this library or error out or what? This may be a good reason to put it underneath their measurement service library and possibly to rename it according to the measurement service name.

2023-06-27 21:53 UTC, jasonmreding commented
I don't know that I have a lot to add here. I don't think either option is going to work all that well if the user wants to add or make modifications to the library and then reference that library from other projects or measurement service implementations from within the same project. Given that, nesting the helper library under each measurement service library should at least eliminate possible cross linking issues. However, I suspect it will also make scripting the template project a lot more difficult once you actually get around to scripting some of the new helpers from the library as part of the generated template.

An alternative to that which would allow sharing the library across measurements within the same project is to generate the library with a name derived from the project name. This will have the same scripting challenges as nesting the library under the measurement service library.

2023-06-27 21:53 UTC, jasonmreding approved these changes

2023-06-28 07:00 UTC, subash-suresh commented on Source/Generator/MeasurementLink Measurement Template/Measurement Service Helpers/Measurement Service Helpers.lvlib
yes joel it is only on disk and we are loading it from disk into our measurement project.
It is not part of the measurement library.

2023-06-28 07:01 UTC, subash-suresh commented on Source/Generator/_Editor/Add Library To Project.vi
Currently if a helper library is already present then the code skips the addition of the helper library in the project

2023-06-28 13:29 UTC, subash-suresh commented
> I don't know that I have a lot to add here. I don't think either option is going to work all that well if the user wants to add or make modifications to the library and then reference that library from other projects or measurement service implementations from within the same project. Given that, nesting the helper library under each measurement service library should at least eliminate possible cross linking issues. However, I suspect it will also make scripting the template project a lot more difficult once you actually get around to scripting some of the new helpers from the library as part of the generated template.
> 
> An alternative to that which would allow sharing the library across measurements within the same project is to generate the library with a name derived from the project name. This will have the same scripting challenges as nesting the library under the measurement service libra

2023-06-28 13:40 UTC, subash-suresh commented
> An alternative to that which would allow sharing the library across measurements within the same project is to generate the library with a name derived from the project name. This will have the same scripting challenges as nesting the library under the measurement service library.

We could generate the measurement helper libraries named based of the measurement name like `nidcpower_service_helpers` or so. Based of the changes in this PR the only change we would be making is the library name input that we pass in the below image and this will successfully create the libraries with the desired name.
![image](https://github.com/ni/measurementlink-labview/assets/98541596/27b72c3a-63bb-4555-bbeb-8ccf3adc0250)

2023-06-28 14:20 UTC, jasonmreding commented
> We could generate the measurement helper libraries named based of the measurement name like nidcpower_service_helpers or so. Based of the changes in this PR the only change we would be making is the library name input that we pass in the below image and this will successfully create the libraries with the desired name.

To allow sharing across measurements in the same project while still avoiding potential cross linking issues with other projects, you would need to generate a name that is unique across projects but stable to any one project. Given that, I'm not sure naming after the measurement would work as that implies you would end up with N copies of the library in the project if there were N measurement services in the project. The only other thing I can think of that is reasonably straight forward is to use the project name as part of the library name in some way. I guess if there is some way to mark or tag a library, you might be able to use that to determine if the helpers library has already been added to the project.

2023-06-28 15:06 UTC, dixonjoel commented on Source/Generator/MeasurementLink Measurement Template/Measurement Service Helpers/Measurement Service Helpers.lvlib
Right, but as a developer, if I opened the template .lvproj, I'd have no idea these exist and the only way I'd know that they're used is to closely inspect the scripting logic. So I'd like to include it in the project for awareness so it's more clear how a dev would edit them and update the template. Is there any drawback to that? As far as I understand, the scripting logic copies the template library specifically and doesn't care what else is in the project in parallel.

2023-06-28 15:08 UTC, dixonjoel commented
Another general comment, we're not changing the actual template measurement to use any of these helpers. So as is, you'd get a measurement service and helpers with no calls into the helpers. It seems like along with this we should modify the scripted measurement to actually call the helpers and have placeholders for a typical measurement service that's targetting hardware with sessions.

2023-06-28 15:10 UTC, jasonmreding commented on Source/Generator/MeasurementLink Measurement Template/Measurement Service Helpers/Measurement Service Helpers.lvlib
If the library name is constant, then this seems reasonable/doable. If the library name is variable, then you're going to have to script adding the library to the generated project with the appropriate name or perform a rename of the library after the initial project is generated.

2023-06-28 16:15 UTC, subash-suresh commented
@sreekantham  and @rfriedma , I have added you to this PR to get your thoughts on this implementation

2023-06-28 18:40 UTC, sreekantham approved these changes

2023-06-29 06:00 UTC, subash-suresh commented
I have closed #230 PR , hence repeating a relevant comment from that PR here.

As per the comments we are seeing the following possible solutions for the placement of this measurement helper library.

Placing the library parallel to the measurement library.(Currently followed in this PR)
Pros
This will be a common helper file for all the measurement libraries in the project.
The naming is common, so it is clear that these helpers are measurement agnostic.
Cons
The helpers cannot be modified to serve the purpose of a single measurement, if there are multiple measurements sharing the same helpers in the project. Modification of the helpers might lead to issues as this is referenced by all the other measurement libraries in the project. This is not an issue if each measurement library is in a separate project file.
Placing the helper library as a nested library.
Pros
This will not have any sort of cross-referencing issues as there will one helper library for each measurement. Which means users are free to add or modify these helpers without worrying about other measurements.
Cons
The naming of the library should be modified to be unique to the measurement, since there can be multiple measurements in the project, and we cannot have similarly named libraries. This will make the helpers look like it is measurement specific.
Placing the library parallel to the measurement library but naming them as per the measurement name.
I am not considering this since this might lead to the creation of multiple helper libraries that sits parallelly along with the measurement libraries.
I went with approach 1, because I wanted to portray this as a measurement agnostic helper library and that it could be used by any measurement in the project. I don't see the need for the users to modify this and if the users wanted to add more helpers that are measurement specific then they can be added in the measurement library itself.

2023-07-05 12:24 UTC, subash-suresh commented
Based on [Jason comments](https://teams.microsoft.com/l/message/19:ba62d31c621842b1b10d9bd1e5a6d8f2@thread.tacv2/1688137464281?tenantId=87ba1f9a-44cd-43a6-b008-6fdb45a5204e&groupId=34b21c30-1dc3-452a-83cd-cb73fcf7aa74&parentMessageId=1688127541516&teamName=MeasurementLink&channelName=TAF-Soliton%20Collaboration&createdTime=1688137464281) in the discussion I have made use of Tags to identify check if the helper library is already present before adding it to the project.

2023-07-11 15:01 UTC, pbirkhol-ni requested changes
There is a MeasurementLink Service Template project. You should add the new library to that project.

2023-07-11 23:48 UTC, jasonmreding commented on Source/Generator/_Editor/Add Helper Library To Project.vi
I agree. I would suggest adding an optional array input of key/value tag pairs to attach to the added library.

2023-07-11 23:53 UTC, jasonmreding commented on Source/Generator/_Editor/Get Measurement Helper Library.vi
I agree that maintaining additional code to check the tag value rather than just the presence of the tag probably doesn't add much value.

2023-07-12 00:21 UTC, jasonmreding commented on Source/Generator/_Editor/Get Measurement Helper Library.vi
Also, you should probably create a constant for the "Measurement Helpers" key. It's annoying, but probably the quickest/cleanest way to do this is to wrap the constant in an inlined sub vi. If you wanted to create some generic enum to string conversion code, I would be OK with that as well, but it's probably overkill until you have lots of constants. At that point, maintaining a single typedef plus helper VI might be preferable to maintaining a file/icon per constant.

2023-07-12 00:25 UTC, jasonmreding commented on Source/Generator/_Editor/Get Measurement Helper Library.vi
The same optimization can be applied to Get Library.vi. You could probably unify these two VIs, but it might not be worth the trouble.

2023-07-12 00:39 UTC, jasonmreding approved these changes

2023-07-14 12:17 UTC, Jayaseelan-James commented on Source/Generator/MeasurementLink Measurement Template/Measurement Service Helpers/Location to Insecure Address.vi
Renamed the input control to Location and made the input Required.

2023-07-14 12:21 UTC, Jayaseelan-James commented on Source/Generator/MeasurementLink Measurement Template/Measurement Service Helpers/Reserve (Poly).vi
I hope, you meant the `gRPC clients` input in the **Unreserve (Poly)** instances.

2023-07-14 13:23 UTC, Jayaseelan-James commented on Source/Generator/_Editor/Add Helper Library To Project.vi
Yeah, makes sense! Have combined `Add Helper Library To Project.vi` with `Add Library to Project.vi` by using a Boolean input to the `Add Library to Project.vi`.

2023-07-14 13:24 UTC, Jayaseelan-James commented on Source/Generator/_Editor/Get Measurement Helper Library.vi
Agreed, @pbirkhol-ni  & @jasonmreding! Have updated the logic to verify if the tag is present. Also, moved the "Measurement Helpers" key to an inline VI :)

2023-07-14 13:45 UTC, Jayaseelan-James commented
Hi @pbirkhol-ni, I have resolved the comments. Please have a check!

2023-07-14 19:35 UTC, pbirkhol-ni commented on Source/Generator/MeasurementLink Measurement Template/Measurement Service Helpers/gRPC Device Options.ctl
The height is now off. You can set an exact height in the control properties. The strings should be 25 pixels high.
![image](https://github.com/ni/measurementlink-labview/assets/57813166/4fe2a637-6b0a-4c9e-8594-8b33c10ef543)

After doing that, right click on the cluster and select `Autosizing >> Arrange Vertically`

2023-07-14 19:36 UTC, pbirkhol-ni commented on Source/Generator/MeasurementLink Measurement Template/Measurement Service Helpers/Location to Grpc Device.vi
Redrop again after fixing my comment above.

2023-07-14 19:36 UTC, pbirkhol-ni commented on Source/Generator/MeasurementLink Measurement Template/Measurement Service Helpers/gRPC Device Options.ctl
Also, make sure this ctl (and all ctls and VIs) are saved in the upper left of the screen.

2023-07-14 19:42 UTC, pbirkhol-ni commented on Source/Generator/_Editor/Add Helper Library To Project.vi
This isn't exactly what Jason had mentioned, although I think what you did is probably okay. Rather than a boolean input for adding a tag, Jason suggested creating an optional input that is an array of key/value pair tags. For the helper library, this array input would have a single element with a key of `Measurement Helpers` and a value of `Measurement Helpers`. For the measurement library, you would leave the input unwired.

2023-07-14 19:47 UTC, pbirkhol-ni commented on Source/Generator/_Editor/Get Measurement Helper Library.vi
Does the Get Lib Tag method throw an error if the tag is present? Comparing against an empty variant is fine, but I would expect the method to error if the tag isn't present. I also see that `Get Lib Tag` seems to return a boolean. If that boolean represents whether the tag is present or not, I would use that instead. Otherwise, the variant comparison is fine.

2023-07-14 19:47 UTC, pbirkhol-ni approved these changes
A lot of VIs are not saved in the top left corner of the screen. Make sure you fix that!

2023-07-16 10:31 UTC, Jayaseelan-James commented on Source/Generator/MeasurementLink Measurement Template/Measurement Service Helpers/gRPC Device Options.ctl
Thanks, fixed it!

2023-07-18 06:47 UTC, Jayaseelan-James commented on Source/Generator/_Editor/Add Helper Library To Project.vi
Okay, I understand. The reasons to go with the Boolean approach as of now is,

1. I'm not foreseeing any use case to add another library project to the template any time in the near future that requires tag name & value to be set. 
2. Also, since this is not a user facing code and is only used to generate the template, I feel okay to proceed with the current changes without complicating the code structure and add/change it in future if required...

2023-07-18 06:58 UTC, merged