Add helpers to get session information based on pin names
ni/measurementlink-labview pull request #233
Opened 2023-06-29 15:55 UTC by subash-suresh

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md).

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This PR adds helpers that allows users to filter session information based on the pin names. 
The following VIs were added to the measurement helpers library.
  1. `Get Sessions and Channels for Pins (N sessions)`
    This vi allows users to get a list of session details based on a list of pin names.
    ![image](https://github.com/ni/measurementlink-labview/assets/98541596/15611b04-684f-447c-92dc-1db0daaad2ae)
    ![image](https://github.com/ni/measurementlink-labview/assets/98541596/d3701545-d2b6-43f5-885d-5470c2ffdc48)
  
    If there are no sessions that match the pin names then an error is thrown.
  2. `Get Session and Channels for Pin (1 Session)`
    This vi allows the users to get a single session based on the given pin name.
    ![image](https://github.com/ni/measurementlink-labview/assets/98541596/42f2d917-0e28-4b5a-8b00-9136bcc3fdeb)
    ![image](https://github.com/ni/measurementlink-labview/assets/98541596/87bbc100-0ff9-4988-a4bd-19e7601d846c)

These VIs have been put in a polymorphic VI as shown below,
![image](https://github.com/ni/measurementlink-labview/assets/98541596/e7e7dd38-833e-425e-be77-0a0a9bfbb363)

These APIs follow a similar structure to the ones in [measurement link python](https://github.com/ni/measurementlink-python/blob/88fe76174039caae9f76d1da015e5d41b06aa9c2/examples/nidcpower_source_dc_voltage/_helpers.py#L267C1-L302C36).
### Why should this Pull Request be merged?

This change will allow users to filter their session information based on pin names, when they reserve multiple sessions at once.

### What testing has been done?

Manually Tested the VIs using the NI-DCPower example

2023-06-29 16:38 UTC, dixonjoel commented
Spelling - 'indices'. Microsoft style guide suggests 'indexes' except for "in the context of mathematical expressions" but I think there may be precendent for NI to use indices.
https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/i/index-indexes-indices

2023-06-29 16:57 UTC, dixonjoel commented
It seems you're adding these helper VIs but not currently calling them from the example. Am I reading that right? Did you then just do your manual testing for DC-Power and revert those changes? I guess it's fine to have these here but not yet be calling them.

2023-06-29 17:02 UTC, dixonjoel approved these changes
Looks good once the couple of minor comments are addressed.

2023-06-29 17:02 UTC, dixonjoel commented on Source/Example Measurements/NI-DCPower Source DC Voltage/Measurement Service Helpers/Get Session and Channels For Pin (1 Session).vi
The [python version](https://github.com/ni/measurementlink-python/blob/main/examples/nidcpower_source_dc_voltage/_helpers.py#L277) checks for exactly equal to 1. You're checking for not greater than 1.

2023-06-29 21:21 UTC, pbirkhol-ni commented on Source/Example Measurements/NI-DCPower Source DC Voltage/Measurement Service Helpers/Get Session and Channels For Pin (1 Session).vi
Yeah, I assume we would want to throw an error for 0 too. I would just wire the array size directly to the case structure with two cases:
![image](https://github.com/ni/measurementlink-labview/assets/57813166/b534b4c7-b5fa-438b-9b17-70fc860a63ac)
![image](https://github.com/ni/measurementlink-labview/assets/57813166/9a32a13c-6b1b-4202-9e01-5f9b5650b875)

2023-06-29 21:28 UTC, pbirkhol-ni commented on Source/Example Measurements/NI-DCPower Source DC Voltage/Measurement Service Helpers/Get Session and Channels For Pin (1 Session).vi
I guess you handle the 0 case in the multi VI and it would make sense that you don't want to override that error. So I think I'm okay with this as is.

2023-06-29 21:41 UTC, pbirkhol-ni commented
> It seems you're adding these helper VIs but not currently calling them from the example. Am I reading that right? Did you then just do your manual testing for DC-Power and revert those changes? I guess it's fine to have these here but not yet be calling them.

As far as I can tell, they aren't used for the python examples either.

2023-06-29 21:43 UTC, pbirkhol-ni approved these changes
I don't really understand the purpose of this PR. Did someone ask for this? I'm afraid that without an example showing how to use these VIs, they just won't get used.

2023-06-30 04:51 UTC, subash-suresh commented
> I don't really understand the purpose of this PR. Did someone ask for this? I'm afraid that without an example showing how to use these VIs, they just won't get used.

This was a feedback from the customer and was pointed out by Jack in one of the PR comments.
We could not find any current examples which could leverage these APIs, we tried to force it in some examples in python but it just made the examples more complicated. Hence we decided not to update the examples

2023-06-30 04:52 UTC, subash-suresh commented
> It seems you're adding these helper VIs but not currently calling them from the example. Am I reading that right? Did you then just do your manual testing for DC-Power and revert those changes? I guess it's fine to have these here but not yet be calling them.

yes joel, that was how it was tested

2023-06-30 12:10 UTC, subash-suresh commented
> Spelling - 'indices'. Microsoft style guide suggests 'indexes' except for "in the context of mathematical expressions" but I think there may be precendent for NI to use indices. https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/i/index-indexes-indices

I have updated indices to indexes

2023-06-30 14:42 UTC, bkeryan approved these changes
Approved with suggestions

Edit: nevermind, I found more issues

2023-06-30 14:42 UTC, bkeryan commented on Source/Example Measurements/Keysight 34401A DMM Measurement/Measurement Service Helpers/Get Sessions and Channels For Pins (N Sessions).vi
> "The given pins and site not found."

Please do one of the following:
- Remove "the" and "." to turn this into a sentence fragment
- Add a verb to turn this into a sentence

2023-06-30 14:43 UTC, bkeryan commented on Source/Example Measurements/Keysight 34401A DMM Measurement/Measurement Service Helpers/Get Session and Channels For Pin (1 Session).vi
The Python version uses singular "channel"
get_session_and_channel_for_pin

2023-06-30 14:43 UTC, bkeryan requested changes

2023-06-30 14:43 UTC, bkeryan commented on Source/Example Measurements/Keysight 34401A DMM Measurement/Measurement Service Helpers/Get Session and Channels (Poly).vi
Both poly instances take N sessions

2023-06-30 14:51 UTC, pbirkhol-ni commented on Source/Example Measurements/Keysight 34401A DMM Measurement/Measurement Service Helpers/Get Session and Channels (Poly).vi
Isn't this expected? I thought only the number of pins would be different between the two instances.

2023-06-30 14:59 UTC, pbirkhol-ni commented on Source/Example Measurements/Keysight 34401A DMM Measurement/Measurement Service Helpers/Get Session and Channels For Pin (1 Session).vi
Renamed.

2023-06-30 15:00 UTC, pbirkhol-ni commented on Source/Example Measurements/Keysight 34401A DMM Measurement/Measurement Service Helpers/Get Sessions and Channels For Pins (N Sessions).vi
Changed to the following for both examples: `Given pins and site not found`

2023-06-30 15:58 UTC, bkeryan commented on Source/Example Measurements/Keysight 34401A DMM Measurement/Measurement Service Helpers/Get Session and Channels (Poly).vi
The VI names have "(1 Session)" and "(N Sessions)"

2023-06-30 16:08 UTC, pbirkhol-ni commented on Source/Example Measurements/Keysight 34401A DMM Measurement/Measurement Service Helpers/Get Session and Channels (Poly).vi
Okay. I renamed the VIs in both examples:
![image](https://github.com/ni/measurementlink-labview/assets/57813166/d768538a-696c-4fba-a83d-5e6d52da5c83)
![image](https://github.com/ni/measurementlink-labview/assets/57813166/aa6b21db-461c-4192-9393-d5804e63b6ba)

2023-06-30 16:22 UTC, bkeryan approved these changes

2023-06-30 16:23 UTC, merged