Update measurement plugin to launch discovery service just-in-time
ni/measurementlink-labview pull request #244
Opened 2023-07-25 14:41 UTC by Jayaseelan-James

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?
This PR updates the measurement plugin to launch discovery service just-in-time before registering to it.

### Why should this Pull Request be merged?
Starting a measurement service when discovery service is not running will throw error `5053 - Failed to read the discovery service key file. Ensure that the discovery service is running.` 

With this PR's changes, discovery service will be launched by the measurement if it is not running.

### What testing has been done?
Manually tested the following the changes for the below cases,
1. Ran a measurement service without DiscoveryService.exe running. Discovery service was launched and the measurement was registered to it.
2. Ran a measurement service with DiscoveryService.exe already running. The measurement was registered to the already running discovery service.

Snapshots of File Changes/Additions:

`Read Discovery Service Key File.vi`:
![Read Disc Service Key File](https://github.com/ni/measurementlink-labview/assets/104884050/154cab55-0208-4a94-8353-4acca563fe4e)

  
`Check and Launch Discovery Service.vi`:
![Check   Launch Discovery Service](https://github.com/ni/measurementlink-labview/assets/104884050/60af586f-b47b-4517-abc6-f45290edba33)

![Check   Launch Discovery Service 2](https://github.com/ni/measurementlink-labview/assets/104884050/c201e781-bf44-4446-b5a8-860f67c2b54e)

  
`Start Discovery Service.vi`:
![Start Discovery Service](https://github.com/ni/measurementlink-labview/assets/104884050/096595bd-8318-4e23-86e6-3d5faf509a6d)
  
![Start Discovery Service 2](https://github.com/ni/measurementlink-labview/assets/104884050/fd5c2d53-e396-453a-9742-cde48ee9043b)

`Error Strings Global.vi`:
![Error Strings Global](https://github.com/ni/measurementlink-labview/assets/104884050/80cb692a-8650-4dbc-9ae8-71292508b911)

2023-07-25 14:50 UTC, dixonjoel commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Start Discovery Service.vi
You'll have to get the Program Files directory from an environment variable and not hard-code it to C:\Program Files. Customers can install NI software to a D: drive for example. See the Python version:
https://github.com/ni/measurementlink-python/blob/942483b17bc3fd718dd16fc94266940ba9dc365e/ni_measurementlink_service/_internal/discovery_client.py#L293

2023-07-25 14:56 UTC, dixonjoel commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Start Discovery Service.vi
I'm not sure offhand what the best way to do this in LabVIEW, but here's one possibility (using the registry)
https://forums.ni.com/t5/LabVIEW/How-do-I-programmatically-find-Program-Files-directory/td-p/205804

2023-07-25 15:00 UTC, dixonjoel commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Start Discovery Service.vi
This seems to work: Use 'Get System Directory.vi'.
![image](https://github.com/ni/measurementlink-labview/assets/38357562/1e38e8f7-8800-460c-9545-c56015584e01)

2023-07-25 15:34 UTC, bkeryan requested changes

2023-07-25 15:34 UTC, bkeryan commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Start Discovery Service.vi
In C# and Python the polling loop opens the key file, rather than merely check that it exists. This may behave differently due to the share mode.

2023-07-25 15:37 UTC, bkeryan commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Start Discovery Service.vi
When this VI is called, the key file path has already been queried. You could pass it in as a parameter.

2023-07-25 16:14 UTC, pbirkhol-ni approved these changes
I don't have much feedback other than what Joel and Brad have already covered.

2023-07-25 16:14 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Start Discovery Service.vi
Perhaps this has already been decided in other implementations, but 30 seconds seems like a long timeout.

2023-07-26 14:26 UTC, Jayaseelan-James commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Start Discovery Service.vi
Thanks for the suggestion, @dixonjoel! I have updated the logic to obtain using the `Get System Directory.vi` but I found that this VI would return `<OS Directory root>:\Program Files (x86)` if it is executed in a 32-bit system. So, I have updated the logic to take the root directory from the `Get System Directory.vi` and append it with `..\Program Files\`. 
![App Files](https://github.com/ni/measurementlink-labview/assets/104884050/35c993ba-7b8e-4f48-9c71-5826cb0df01a)

2023-07-26 14:28 UTC, Jayaseelan-James commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Read Discovery Service Key File.vi
Agreed. Updated the logic to invoke the VI in `Get Discovery Service.vi`.

2023-07-26 14:28 UTC, Jayaseelan-James commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Check and Launch Discovery Service.vi
Updated. Thanks for the suggestion!

2023-07-26 14:30 UTC, dixonjoel commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Start Discovery Service.vi
No that doesn't seem correct. The whole point is to get the correct program files directory where things are installed independent of drive path or whether it's 64 bit or 32 bit. So I think you should take it as is and append 'National Instruments\Shared\MeasurementLink'. You don't have a 32-bit system where it's installed in c:\program files do you?

2023-07-26 14:30 UTC, Jayaseelan-James commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Check and Launch Discovery Service.vi
Fixed it.

2023-07-26 14:33 UTC, Jayaseelan-James commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Start Discovery Service.vi
Yeah, that's right. Since there was only one path separator, I didn't wire the `replace all?` but yeah considering any future changes, I have now wired it!

2023-07-26 14:36 UTC, Jayaseelan-James commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Start Discovery Service.vi
Yes! `Strip Path` requires the path separator's to be proper, which is used to provide the working directory to launch the Discovery Service at the right port. Hence, I'm leaving it untouched.

2023-07-26 14:41 UTC, Jayaseelan-James commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Check and Launch Discovery Service.vi
Updated the File name to `Ensure Discovery Service Started.vi`, but I would like to understand the reason behind naming it as "ensure discovery service started", because I feel that internally what we do reflects the statement, "Check and Launch Discovery Service". ?

2023-07-26 14:42 UTC, Jayaseelan-James commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Start Discovery Service.vi
Updated the flow to check by opening the key file & close it once it's found.

2023-07-26 14:43 UTC, Jayaseelan-James commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Error Strings Global.vi
Updated the error message to `Timed out waiting for discovery service to start.`

2023-07-26 14:44 UTC, Jayaseelan-James commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Start Discovery Service.vi
@bkeryan, @pbirkhol-ni Bit curious to know the reason behind settling with a 30secs timeout?!

2023-07-26 15:19 UTC, Jayaseelan-James commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Start Discovery Service.vi
If I understand correct, MeasurementLink runs on `64-bit` machine and so is Discovery Service, right? In that case, if the user for any reason uses LabVIEW 32-bit version on a 64-bit machine, it would give us `<Root>:\Program Files (x86)\` but the discovery service will be present in `<Root>:\Program Files\`. 

Please correct me if I'm wrong.

PS: Sorry that I mentioned it as 32-bit system in my earlier comment instead of 32-bit LabVIEW application.

2023-07-26 15:28 UTC, Jayaseelan-James commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Start Discovery Service.vi
Also, now I have added an target type check!
![image](https://github.com/ni/measurementlink-labview/assets/104884050/1444aa16-f2a3-4e00-88b7-d060b9058159)

2023-07-26 15:37 UTC, dixonjoel commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Start Discovery Service.vi
We don't generally support 32 bit LabVIEW versions so I don't think you need the hard-coded Program Files here.

2023-07-26 15:53 UTC, Jayaseelan-James commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Start Discovery Service.vi
Ohh, Sure! Removed the hard-coded Program files.
![image](https://github.com/ni/measurementlink-labview/assets/104884050/eec0ea51-9cc0-4a6c-920f-5275b6764aae)

2023-07-26 16:01 UTC, dixonjoel approved these changes

2023-07-26 22:48 UTC, bkeryan commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Start Discovery Service.vi
The timeout was originally added in ASW PR 276020. Maybe @Vasantha-Kumar-J remembers?

Anyway, I think 30 seconds is fine. The discovery service should never take more than 30 seconds to start, even on a heavily loaded machine, except when you have a debugger attached. And it's short enough that users will likely see a timeout error before they can open Task Manager and kill the process.

2023-07-26 22:50 UTC, bkeryan commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Check and Launch Discovery Service.vi
If the discovery service is still running, opening for write should fail, which prevents deleting the key file. See the discussion in ASW PR 276020.

2023-07-26 22:55 UTC, bkeryan commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Check and Launch Discovery Service.vi
"ensure discovery service started" describes the purpose of the function. The post-condition is that the discovery service has been started. (I guess "running" is even better, since "running" is a state and "start" is a state transition, but whatever.)

"check and launch discovery service" describes the implementation. Also, what does it check? And it doesn't always launch the discovery service, so you end up renaming it to "check whether key file exists and launch the discovery service if needed", which is much more verbose.

2023-07-27 13:38 UTC, Jayaseelan-James commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Check and Launch Discovery Service.vi
Sure, Understood.

2023-07-27 13:40 UTC, Jayaseelan-James commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Check and Launch Discovery Service.vi
Updated the check, @bkeryan. Please review and let me know if any further changes are required.
![image](https://github.com/ni/measurementlink-labview/assets/104884050/591d7853-d782-4663-9310-e8923aa789b0)

2023-07-27 19:20 UTC, bkeryan requested changes

2023-07-27 19:20 UTC, bkeryan commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Get Discovery Service Address.vi
This VI sometimes returns error 7, "File not found" without starting the discovery service.

Steps:
- Click the **Run Continuously** button
- Open **Task Manager** and kill the discovery service
- The VI error out will temporarily change to 7

If you add a probe to `Ensure Discovery Service Started.vi` where it clears the error, you will see the probe change from 5 to 7. The error code path does not start the discovery service.

2023-07-27 19:20 UTC, bkeryan commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Ensure Discovery Service Started.vi
[style] FYI, the rest of these VIs use lowercase control/indicator labels, but I guess this component is inconsistent about that

2023-07-28 05:25 UTC, Jayaseelan-James commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Start Discovery Service.vi
Thanks for the info, I'll update it!

2023-07-28 12:45 UTC, Jayaseelan-James commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Get Discovery Service Address.vi
Thanks for point it out. I have updated the logic in `Ensure Discovery Service Started.vi` to handle the `Error 7: File not found.`

2023-07-31 14:58 UTC, bkeryan approved these changes

2023-07-31 14:58 UTC, bkeryan commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Start Discovery Service.vi
FYI: this loop's error wire doesn't have a shift register.

![image](https://github.com/ni/measurementlink-labview/assets/17914399/d8274120-34e7-46b8-894c-f2c17056b7bf)

However, it's not a problem in this case because the loop breaks when there is an error.

If the loop didn't break when there is an error, then a shift register would be necessary to pass the error to the next loop iteration.

2023-07-31 14:58 UTC, bkeryan commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Open Discovery Service Key File.vi
You didn't answer my previous question:

> Can you achieve the same goal by calling `Read Discovery Service Key File.vi` instead of splitting it up?

Instead, you changed this code to open the file for write instead of opening it for read+share:

![image](https://github.com/ni/measurementlink-labview/assets/17914399/115836c4-1683-4b8a-b72f-7e910bb46b62)

Does this introduce any new problems? The most obvious one is a race condition that prevents the discovery service from writing the key file. If this code used `open or create`, it would create a new key file. If the discovery service tried to write the key file while this code had the key file open, then I think it would get an error.

However, since you used `open`. I guess it's okay.

2023-07-31 14:58 UTC, bkeryan commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Get Discovery Service Address.vi
Ok, I can't reproduce this problem anymore. Good.

2023-07-31 16:50 UTC, merged