Implement IInstrument for DMM
ni/measurementlink-labview pull request #297
Opened 2023-09-28 21:50 UTC by gpachecoNI

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

 - Creates an implementation of IInstrument for NI-DMM
 - Adds Tests for the Create / Attach / Detach and Close

Based on the NI-Digital

### Why should this Pull Request be merged?

Implements the following US AB#2533859

### What testing has been done?

Auto Tests pass

2023-09-28 22:30 UTC, gpachecoNI commented on Source/Runtime/MeasurementLink niDMM/Instrument/Close MeasurementLink Session.vi
![Uploading image.png…]()

2023-09-28 22:36 UTC, jasonmreding approved these changes

2023-09-28 22:53 UTC, dixonjoel commented
There are 0 checks on this PR, presumably because of the branch conflicts.  Please ensure the checks run and the G tests pass before submitting. I'd like to do a last quick check after the conflicts are resolved, so you can mention me when that's done.

2023-09-28 22:54 UTC, gpachecoNI commented on Source/Runtime/MeasurementLink niDMM/Instrument/Create.vi
![image](https://github.com/ni/measurementlink-labview/assets/111389775/0e553565-c400-4ef6-82bd-73fa1d18267c)

2023-09-28 22:56 UTC, gpachecoNI commented on Source/Runtime/MeasurementLink niDMM/Instrument/Get Instrument Type ID.vi
![image](https://github.com/ni/measurementlink-labview/assets/111389775/7eee9fb4-24e9-439f-8748-9bd4c8a77775)

2023-09-28 22:56 UTC, gpachecoNI commented on Source/Runtime/MeasurementLink niDMM/Instrument/Get Provided Interface.vi
![image](https://github.com/ni/measurementlink-labview/assets/111389775/612a3dd1-865f-4921-bbe9-818a2688f70b)

2023-09-28 22:56 UTC, gpachecoNI commented on Source/Runtime/MeasurementLink niDMM/Instrument/Initialize MeasurementLink Session.vi
![image](https://github.com/ni/measurementlink-labview/assets/111389775/baa816a0-6883-4a5f-8a5b-dcd6acbc9444)

2023-09-29 00:47 UTC, pbirkhol-ni requested changes
Something is wrong with your project and/or libraries. I see this when I load the project.

![image](https://github.com/ni/measurementlink-labview/assets/57813166/d5e1653d-7a5b-4ab3-bb0a-05b8aacceee6)

Merge conflicts are hard in LabVIEW, even for text files. I have had the most luck by reverting all of my changes to projects and libraries. You can do this by removing your new library and tests from the project and saving all. Then merge in main and you shouldn't have any merge conflicts. Then re-add your new library and test VIs. This sounds silly, but it's fast and almost guaranteed to work. It won't work as well if you are modifying existing VIs, but that isn't the case here.

2023-09-29 16:39 UTC, gpachecoNI commented
> use of the branch conflicts. Please ensure the checks run and the G tests pass before submitting. I'd like to do a last quick check after the conflicts are resolved, so y

@dixonjoel

2023-09-29 16:49 UTC, pbirkhol-ni approved these changes

2023-09-29 17:39 UTC, WesleyTangNationalInstruments commented
Minor: There are some inconsistencies in the capitalization of "DMM" vs "Dmm" in folder names. For the tests, the Virtual Folder is "niDmm" while the disk folder is "niDMM".

measurement-services-labview\Source\Tests\Tests.Runtime\Measurement Server\niDMM

![image](https://github.com/ni/measurementlink-labview/assets/103216564/6d134303-1100-4d0f-b044-de08d1456bcd)

2023-09-29 17:58 UTC, dixonjoel approved these changes

2023-09-29 18:26 UTC, merged