Initial set of MeasurementLink palette files
ni/measurementlink-labview pull request #325
Opened 2023-10-09 22:08 UTC by dixonjoel

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Add palette files to the repo with basic content for measurement context, session management, and a Create Session / Get Connections / Create Instrument subpalette for each of the 5 drivers. These aren't yet integrated into the package build spec so they won't have any effect right now.
Looks like this:
<img width="808" alt="image" src="https://github.com/ni/measurementlink-labview/assets/38357562/eee329e6-5307-4b40-afab-131cb3b45bc7">

### Why should this Pull Request be merged?

Begin to make the MeasurementLink LabVIEW API for measurement services.

### What testing has been done?

Manual editing and dropping VIs from the palettes.

2023-10-09 22:08 UTC, dixonjoel commented on Source/Runtime/MeasurementLink_FGEN.mnu
Fix the short name of 'Create.vi'...

2023-10-10 15:24 UTC, pbirkhol-ni requested changes

2023-10-10 15:24 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink.mnu
I can't figure out how to organize these on disk such that they show up correctly in LabVIEW. I eventually got _something_ working, but it isn't right. I realize that our installer will handle this for us, but maybe we can organize the palette files in source that same way we expect them to be installed?

2023-10-10 15:24 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink_DCPower.mnu
I don't think the Create Instrument VIs should be on the palette.

2023-10-10 15:24 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink.mnu
You also should put `Create Session.vim` on the palette.

2023-10-10 15:24 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink.mnu
You should put the 3 Get Connections.vim malleable VIs on the palette. I feel like we should hide the Create Sessions.vim and Get Connections.vim in an Advanced palette or something like that. Those VIMs are only valuable for customers who are trying to implement support for 3rd party devices.

2023-10-10 15:24 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink.mnu
We will need to do a better job customizing the palettes in the right click menu. I don't think you even attempted to do that in this PR, which is fine.

2023-10-10 15:24 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink.mnu
I don't know what to do with the `Session Reservation.Reserve Sessions.vi.` For one, it is community scoped, so customers can't even use it. However, it is valuable for code modules. Maybe we can put it on a `Code Module` subpalette and make it public? @jasonmreding has thought about this more than I have.

2023-10-10 15:24 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink.mnu
We'll eventually have a Generic Get Connections VI and a Generic Get Session Infos VI. We don't have to add those now, but we should make sure they fit your proposal, and I think they do. They could go on a different subpalette similar to the NI Digital or NI DCPOWER subpalettes.

2023-10-10 15:24 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink.mnu
It's weird that the context helper shows a generic class wire when hovering over a VI in the palette. As soon as a drop the VI on the diagram, the context help gets updated to show the correct class wire. This seems like something that is fixable, but I don't know how.

![image](https://github.com/ni/measurementlink-labview/assets/57813166/af4bb75e-54a4-4584-a716-352c18edcad6)

2023-10-10 19:02 UTC, jasonmreding commented on Source/Runtime/MeasurementLink.mnu
I think we still need an explicit decision as to whether we are going to maintain individual .mnu source files using traditional mechanisms in LV to create/edit the files or whether we are going to use VIPB to create/edit the menu files. In the latter case, all of the menu files seem to be stored in the .vipb binary file itself. 

I also think we need a better understanding of how we are going to maintain the right click context menus for classes/libraries vs. the the functions palette menus. Does it require duplication of the menu file(s) or can we reference the same menu file(s) from multiple locations? There is probably some research / prototyping that needs to happen in this regard. The VIPB palette editor is much nicer in a lot of ways, but it doesn't offer all of the advanced features that LV exposes. However, I don't know if we will need/want any of these advanced features.

If we are going to maintain our .mnu files in source, then it would make more sense to me to keep them all in a directory structure like "menus\Categories\Measurement" which matches their desired installation hierarchy relative to the LV root directory. However, before finalizing that, I would like to understand the strategy for specifying the right click context menus vs. functions palette menus. It might be that it makes more sense to have the .mnu files in source next to their respective class/library file where the file is added to the class/library and configured in the class/library settings to be the palette for the class/library. Then under the functions palettes, we just link to the existing class/library palette files where appropriate. Creating/editing this will probably have to be done from a pseudo-install setup so that things are linking to <vilib> and not relative paths from the source directory.

2023-10-10 19:06 UTC, jasonmreding commented on Source/Runtime/MeasurementLink.mnu
Ultimately, I think the API should be made public so that it can be used from code modules. The same is true for register/unregister session APIs. However, the positioning/naming of this palette relative to the MeasurementContext based APIs is still listed as an open issue in the HLD I posted. If you want to propose/discuss a solution here, go for it. Otherwise, we should expect to revisit whatever is done here at some point in the future.

2023-10-10 19:13 UTC, jasonmreding commented on Source/Runtime/MeasurementLink_DCPower.mnu
One question that pertains to all the driver specific palettes is whether the palette/short names should match what the actual driver uses? If the answer is yes, then we need to tweak things here. It's not consistent, but most of the drivers use all caps with a space instead of a hyphen for the sub-palette name when viewed from the parent palette. The exceptions I'm aware of are "NI Digital" and "NI DAQmx" which don't use all caps. 

Once you navigate into the driver palette, the name of the palette then uses a hyphen instead of a space in the name (I don't know why). "NI DCPOWER" also becomes "NI-DCPower". Maybe this isn't worth sweating over, but I thought I would bring it up.

2023-10-10 19:24 UTC, jasonmreding reviewed
I think @pbirkhol-ni and I are somewhat add odds at the moment in regards to feedback as to what should and should not be on the palette. I'm still open to arguments on this, but these are my current thoughts on the issue:
- Driver specific `Create Instrument` should not be on the palette.
- No .vims that are used to implement driver specific `IInstrument` plugins should be on the palette. I think it's too much noise/confusion for the average user. Instead, we can steer plugin authors to our implementations on the palette (nothing is password protected) and/or we can create a project template that we install as a getting started guide for these customers.
- I don't think we should initially put any generic `Get Connections` API on the palette that returns a variant session. I would rather wait for user feedback before adding them, as I'm not convinced they are needed and might cause confusion.

2023-10-10 19:27 UTC, jasonmreding requested changes
I want to have a clearer plan on how we are going create/edit mnu files before approving.

2023-10-10 19:27 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink_DCPower.mnu
The MI drivers are so inconsistent. I'd rather be consistent within our own palette. Ideally, that would mean using the official driver names like `NI-DCPower`, `NI-FGEN`, etc.

2023-10-10 20:27 UTC, pbirkhol-ni requested changes

2023-10-10 20:27 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink.mnu
From Jason:

> I think @pbirkhol-ni and I are somewhat add odds at the moment in regards to feedback as to what should and should not be on the palette. I'm still open to arguments on this, but these are my current thoughts on the issue:
> - Driver specific Create Instrument should not be on the palette.
> - No .vims that are used to implement driver specific IInstrument plugins should be on the palette. I think it's too much noise/confusion for the average user. Instead, we can steer plugin authors to our implementations on the palette (nothing is password protected) and/or we can create a project template that we install as a getting started guide for these customers.
> - I don't think we should initially put any generic Get Connections API on the palette that returns a variant session. I would rather wait for user feedback before adding them, as I'm not convinced they are needed and might cause confusion.

2023-10-10 20:27 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink.mnu
> Driver specific Create Instrument should not be on the palette.

We agree on this.

> No .vims that are used to implement driver specific IInstrument plugins should be on the palette.

I don't completely disagree here. However, 3rd party instrument support has been a requirement for every single customer that I have talked to, so we should at least consider promoting it on the palette. We could have a separate top level palette for developing 3rd party instrument support. I'm not sure that makes things any less confusing, though.

> I don't think we should initially put any generic Get Connections API on the palette

This is fine.

2023-10-10 22:08 UTC, dixonjoel commented on Source/Runtime/MeasurementLink_DCPower.mnu
This is different from the HLD, right? I was trying to follow this:
https://dev.azure.com/ni/DevCentral/_git/ASW/pullrequest/562608

2023-10-10 22:09 UTC, dixonjoel commented on Source/Runtime/MeasurementLink.mnu
Yeah, I'm trying to understand how that even works. I can't seem to find any documentation on right-click palettes for classes / libraries / etc. Do you have any knowledge of that?

2023-10-10 22:11 UTC, dixonjoel commented on Source/Runtime/MeasurementLink.mnu
This is the first I'm learning about the VIPM options for palette files. I'm playing with that, but it seems to me that the whole MeasurementLink functions palette could be defined in the .vipb and that would not require us to store .mnu files in source.

I don't know how right-click menus for classes / libraries work yet so I can't comment on that yet, but I don't see any way to define that in the .vipb unless I'm missing something. So for those, if it's true that you just place a .mnu file under the class to define it, then we'd just keep it next to the class there.

2023-10-11 00:32 UTC, dixonjoel commented on Source/Runtime/MeasurementLink.mnu
My current intention is to edit the .vipb to create the MeasurementLink palette under Measurement I/O so we won't have to manage those files.

And then keep the class .mnu file next to the class in source.

For this PR, my intention is to do only the top level MeasurementLink palette and not the driver subpalettes so we can have a small chunk to review.

2023-10-11 00:33 UTC, dixonjoel commented on Source/Runtime/MeasurementLink.mnu
I know how this works now and have been able to get a .mnu file working with the class. But I'll defer that to another PR.

2023-10-11 00:45 UTC, dixonjoel commented on Source/Runtime/MeasurementLink.mnu
Future PR

2023-10-11 01:19 UTC, jasonmreding commented on Source/Runtime/MeasurementLink.mnu
> I don't know how right-click menus for classes / libraries work yet so I can't comment on that yet, but I don't see any way to define that in the .vipb unless I'm missing something. So for those, if it's true that you just place a .mnu file under the class to define it, then we'd just keep it next to the class there.

Yes, VIPB supports this although I don't find it to be that intuitive. Check the documentation which alludes to this. If I remember correctly, I think you have to define a unique Palette Set per class/library which then automatically gets added to the class as part of the build process. I haven't played with this much so I could be wrong about how it works, but the capability is definitely supported in some fashion.

![image](https://github.com/ni/measurementlink-labview/assets/103200169/d61002e3-e037-4713-bcaa-8453992e1f53)

2023-10-11 01:21 UTC, jasonmreding commented on Source/Runtime/MeasurementLink_DCPower.mnu
The HLD was a rough first pass and not a finished product. I think in the intervening time, we are leaning towards leaving it off the palette based on what we know now.

2023-10-11 01:25 UTC, jasonmreding commented on Source/Runtime/MeasurementLink.mnu
>>    No .vims that are used to implement driver specific IInstrument plugins should be on the palette.

> I don't completely disagree here. However, 3rd party instrument support has been a requirement for every single customer that I have talked to, so we should at least consider promoting it on the palette. We could have a separate top level palette for developing 3rd party instrument support. I'm not sure that makes things any less confusing, though.

I am currently leaning towards the idea of shipping a template project for creating a third party driver plugin or just telling people to use the NI specific driver wrappers we ship as a template. I'm not necessarily opposed to placing them on the palette. However, the vast majority of users will never need them, and it would reduce noise in what is becoming a very large palette hierarchy.

2023-10-12 14:31 UTC, dixonjoel commented on Source/Runtime/MeasurementLink.mnu
Later PR

2023-10-12 14:32 UTC, dixonjoel commented on Source/Runtime/MeasurementLink.mnu
Postponing and starting with measurement context.

2023-10-12 14:32 UTC, dixonjoel commented on Source/Runtime/MeasurementLink.mnu
To be addressed in a later PR.

2023-10-12 14:38 UTC, dixonjoel commented on Source/Runtime/MeasurementLink.mnu
Later PR

2023-10-12 14:39 UTC, dixonjoel commented on Source/Runtime/MeasurementLink_DCPower.mnu
I'll plan on using the 'official driver names' going forward.

2023-10-12 14:45 UTC, dixonjoel commented on Source/Runtime/MeasurementLink.mnu
I'll keep these in mind for the future PRs

2023-10-12 16:05 UTC, pbirkhol-ni approved these changes

2023-10-13 00:57 UTC, jasonmreding commented
This seems reasonable for an initial submission. I still have questions as to whether we will want a sub-palette for the MeasurementContext APIs or not. If we do, then it seems like there is opportunity to share the same .mnu file for the functions palette and the class right click context palette.

2023-10-13 00:57 UTC, jasonmreding approved these changes

2023-10-13 14:13 UTC, merged