Creating NI-SCOPE Acquire Waveform example.
ni/measurementlink-labview pull request #329
Opened 2023-10-11 16:05 UTC by DelpireNI

- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Creates an NI-SCOPE example that demonstrates how to use our new session management APIs with NI-SCOPE and acquire a waveform.

### Why should this Pull Request be merged?

We want to have examples demonstrating how to use our new session management APIs with each of our device drivers. 

### What testing has been done?

Example runs successfully and returns waveform data.

2023-10-11 16:09 UTC, DelpireNI commented on Source/Example Measurements/NI-SCOPE Aquire Waveform/NI-SCOPE Acquire Waveform/Measurement Configuration.ctl
Other examples seem to have the default values in this file. I have tried on two different occasions to set them here, but every time I save and close the project they are cleared. They do not show up when loading in InstrumentStudio.

Does anyone know what I need to do to get default values in a LabVIEW measurement?

2023-10-11 16:26 UTC, jasonmreding commented on Source/Example Measurements/NI-SCOPE Aquire Waveform/NI-SCOPE Acquire Waveform/Measurement Configuration.ctl
You are doing this?

![image](https://github.com/ni/measurementlink-labview/assets/103200169/1652b648-99a6-4add-8b2e-6927ed54f7cc)

 or

![image](https://github.com/ni/measurementlink-labview/assets/103200169/bfdff083-e77a-48c9-afb5-292082f517f3)

2023-10-11 16:28 UTC, DelpireNI commented on Source/Example Measurements/NI-SCOPE Aquire Waveform/NI-SCOPE Acquire Waveform/Measurement Configuration.ctl
I didn't even know that was on option! I'll give it a try, thank you!

2023-10-11 16:42 UTC, synesthetize commented on Source/Example Measurements/NI-SCOPE Aquire Waveform/NI-SCOPE Acquire Waveform/Measurement Configuration.ctl
You need to set your default values in the `Measurement Configuration.ctl` and then before saving you need to go to Edit -> "Make Current Values Default".

2023-10-11 20:13 UTC, pbirkhol-ni requested changes
I need to install NI-SCOPE to finish this review. I figured I'd post my initial comments first, though.
Make sure you also work on the TestStand aspect of the example.

2023-10-11 20:13 UTC, pbirkhol-ni commented on Source/Example Measurements/NI-SCOPE Aquire Waveform/NI-SCOPE Acquire Waveform/Measurement UI.vi
If you're feeling crazy, I think you can probably programmatically update the Plot Legend for the graph to match the pin inputs.  :)

2023-10-11 20:14 UTC, DelpireNI commented
> I need to install NI-SCOPE to finish this review. I figured I'd post my initial comments first, though. Make sure you also work on the TestStand aspect of the example.

I was thinking we could do the TestStand work in a separate PR.

2023-10-11 20:25 UTC, DelpireNI commented on Source/Example Measurements/NI-SCOPE Aquire Waveform/NI-SCOPE Acquire Waveform/NI-SCOPE Acquire Waveform.lvlib
Fixed. Hopefully I caught all of them.

2023-10-11 20:25 UTC, DelpireNI commented on Source/Example Measurements/NI-SCOPE Aquire Waveform/Measurement Service Helpers/Measurement Service Helpers.lvlib
I did not use anything from there. I think this is generated from our generation tool. I deleted the helpers and removed the reference from the project and the example still runs correctly.

2023-10-11 20:26 UTC, DelpireNI commented on Source/Example Measurements/NI-SCOPE Aquire Waveform/NI-SCOPE Acquire Waveform/Get Measurement Details.vi
Fixed:
![image](https://github.com/ni/measurementlink-labview/assets/71399316/ab2ae530-e028-4992-ab8f-054cfb1e3025)

2023-10-11 20:57 UTC, DelpireNI commented on Source/Example Measurements/NI-SCOPE Aquire Waveform/NI-SCOPE Acquire Waveform/Measurement UI.vi
Felt crazy! This seems to work just fine:

![image](https://github.com/ni/measurementlink-labview/assets/71399316/bf3d8431-a510-4f31-8e75-9bfdedd652f8)

2023-10-11 21:33 UTC, pbirkhol-ni approved these changes

2023-10-11 21:33 UTC, pbirkhol-ni commented on Source/Example Measurements/NI-SCOPE Acquire Waveform/NI-SCOPE Acquire Waveform/Run Service.vi
Can you customize the icon for this VI like we did for DCPower?

2023-10-11 21:33 UTC, pbirkhol-ni commented on Source/Example Measurements/NI-SCOPE Aquire Waveform/NI-SCOPE Acquire Waveform/Measurement UI.vi
Not crazy enough. I was thinking something like this:
![image](https://github.com/ni/measurementlink-labview/assets/57813166/e593eb36-96a4-4ff8-9cea-d88241383364)

That will update the Plot Legend with the names of the pins too.

2023-10-11 21:33 UTC, pbirkhol-ni commented on Source/Example Measurements/NI-SCOPE Acquire Waveform/NI-SCOPE Acquire Waveform/Measurement Logic.vi
I noticed that if I set my Pin Names to Pin1, Pin2, Pin3 and then set my Trigger Source to Pin4, I get an error about Pin4 not having any connections, which is correct since we didn't reserve Pin4. Should the measurement be adding the trigger source to the list if pins to reserve if it isn't already in the list?

2023-10-11 21:33 UTC, pbirkhol-ni commented on Source/Example Measurements/NI-SCOPE Acquire Waveform/NI-SCOPE Acquire Waveform/Measurement Logic.vi
The DCPower example requires a persistent simulated device or a real device, whereas this example creates a session-based simulated device. I don't think using a session-based simulated device is the right thing to do unless there is a discoverable way for customers to modify the example to use real hardware. I think @bkeryan has had similar conversations recently for python. Did we make any official decisions for how to handle this in python?

2023-10-11 21:37 UTC, DelpireNI commented on Source/Example Measurements/NI-SCOPE Aquire Waveform/NI-SCOPE Acquire Waveform/Measurement UI.vi
That is even crazier.

2023-10-11 23:18 UTC, bkeryan commented on Source/Example Measurements/NI-SCOPE Acquire Waveform/NI-SCOPE Acquire Waveform/Measurement Logic.vi
The current plan is to configure simulation by setting environment variables or creating a `.env` file: https://github.com/ni/measurementlink-python/blob/main/.env.simulation

This way, the examples will use real hardware by default, and you can enable simulation by copying one file.

2023-10-12 15:15 UTC, DelpireNI commented on Source/Example Measurements/NI-SCOPE Aquire Waveform/NI-SCOPE Acquire Waveform/Measurement UI.vi
Added this. Works great. :)

2023-10-12 15:20 UTC, DelpireNI commented on Source/Example Measurements/NI-SCOPE Acquire Waveform/NI-SCOPE Acquire Waveform/Measurement Logic.vi
Okay I fixed this by adding the Trigger source to the list of pins, removing duplicates, and then passing that into reserve pins. I just realized though that this will mean all the pins will come out of Create Sessions' channel list. So I need to update it to call Get Connections for the pins we want to use.

2023-10-12 16:34 UTC, DelpireNI commented on Source/Example Measurements/NI-SCOPE Acquire Waveform/NI-SCOPE Acquire Waveform/Measurement Logic.vi
This should now be resolved. Trigger source will get reserved, and will not be used if it isn't in the Pin Names parameter.

2023-10-12 18:18 UTC, pbirkhol-ni approved these changes

2023-10-12 18:18 UTC, pbirkhol-ni commented on Source/Example Measurements/NI-SCOPE Acquire Waveform/NI-SCOPE Acquire Waveform/Measurement Logic.vi
I would remove the False boolean that is wired to Create Sessions. Reset is false by default, so explicitly wiring it just causes unnecessary clutter.

2023-10-12 18:18 UTC, pbirkhol-ni commented on Source/Example Measurements/NI-SCOPE Acquire Waveform/NI-SCOPE Acquire Waveform/Measurement Logic.vi
I don't think you should put Initiate and Fetch in the same for loop. That effectively serializes the measurement. It will also call Initiate multiple times on the same session. Instead, Initiate shouldn't be in a for loop and should use the session from Create Sessions. Then you should call Fetch in the for loop.

2023-10-12 18:18 UTC, pbirkhol-ni commented on Source/Example Measurements/NI-SCOPE Acquire Waveform/NI-SCOPE Acquire Waveform/Measurement Logic.vi
If you had multiple sessions, the only thing that would change is that you would Initiate in its own for loop.

2023-10-12 18:18 UTC, pbirkhol-ni commented on Source/Example Measurements/NI-SCOPE Acquire Waveform/NI-SCOPE Acquire Waveform/Get Type Specializations.vi
The icon for this VI has a weird overlay.

2023-10-12 18:18 UTC, pbirkhol-ni commented on Source/Example Measurements/NI-SCOPE Acquire Waveform/NI-SCOPE Acquire Waveform.lvproj
There is some inconsistency between your example and the NI-FGEN and NI-DCPower examples. Those examples condense the project name and library name into a single string with no spaces. I don't know why it is done that way and I don't think one way is necessarily preferable over another, but we should be consistent.

2023-10-12 18:22 UTC, DelpireNI commented on Source/Example Measurements/NI-SCOPE Acquire Waveform/NI-SCOPE Acquire Waveform/Measurement Logic.vi
I was going to leave it out originally, but that won't work if we have multiple sessions. I guess this won't work for multiple sessions unless you replace Create Sessions with a Multiple session variant.

I'll go ahead and remove it from the loop.

2023-10-12 18:22 UTC, DelpireNI commented on Source/Example Measurements/NI-SCOPE Acquire Waveform/NI-SCOPE Acquire Waveform.lvproj
I'll remove the spaces.

2023-10-12 20:20 UTC, DelpireNI commented on Source/Example Measurements/NI-SCOPE Acquire Waveform/NI-SCOPE Acquire Waveform.lvproj
Files have been renamed. :)

2023-10-12 20:32 UTC, pbirkhol-ni commented
Also make sure you try building the measurement into an exe and running it that way. You don't necessarily have to run it as a static measurement. You can just build it into an exe, run it, and then open it using InstrumentStudio.

2023-10-12 20:49 UTC, pbirkhol-ni commented on Source/Example Measurements/NI-SCOPE Acquire Waveform/NI-SCOPE Acquire Waveform/Measurement Logic.vi
The other examples are using 60000 as the timeout for Reserve.

2023-10-12 21:12 UTC, DelpireNI commented on Source/Example Measurements/NI-SCOPE Acquire Waveform/NI-SCOPE Acquire Waveform/Measurement Logic.vi
Done:
![image](https://github.com/ni/measurementlink-labview/assets/71399316/8c28ab5d-20a8-471e-9585-096293bf29f6)

2023-10-12 21:12 UTC, DelpireNI commented
> Also make sure you try building the measurement into an exe and running it that way. You don't necessarily have to run it as a static measurement. You can just build it into an exe, run it, and then open it using InstrumentStudio.

Tried this out and it worked just fine. :)

2023-10-12 22:42 UTC, merged