Implement auto-unreserve via observer callbacks
ni/measurementlink-labview pull request #347
Opened 2023-10-17 20:41 UTC by jonathanmendez

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

- Adds an observer interface to the `Session Reservation` class to notify which session infos are reserved and unreserved
- Implements the observer interface with the `MeasurementContext` to keep track of any session infos to automatically unreserve after the measurement logic, if the sessions are reserved using the `Measurement Context:Reserve Sessions` VIs

### Why should this Pull Request be merged?

We want to implement automatic unreserving of sessions as an aid for users, particularly to avoid "zombie" session reservations that are hard to get rid of and block the system.

### What testing has been done?

Manually tested using the NI-DCPower example that was modified to use the new session reservation APIs.

2023-10-17 21:40 UTC, jonathanmendez commented on Source/Runtime/MeasurementLink Session Management/Session Reservation/Reserve Sessions with Observer.vi
This is a copy/paste of `Reserve Sessions.vi` with the observer code added. I did not put much effort into making this clean because it will have to change based on the refactoring done as part of #337

2023-10-17 23:28 UTC, jasonmreding commented on Source/Runtime/MeasurementLink Session Management/Session Reservation/Reserve Sessions with Observer.vi
This has been submitted now. There really weren't any code changes made other than making the API public and updating some documentation.

2023-10-17 23:30 UTC, jasonmreding commented on Source/Runtime/MeasurementLink Measurement Server/Classes/MeasurementContext/Data.ctl
This is a nit, but I would call the field "reserved session infos" rather than "session infos to unreserve".

2023-10-17 23:34 UTC, jasonmreding commented on Source/Runtime/MeasurementLink Measurement Server/Classes/MeasurementContext/Destroy.vi
We should probably update this VI for shared clone reentrant execution since measurement calls can be invoked in parallel.

2023-10-18 00:01 UTC, jasonmreding commented on Source/Runtime/MeasurementLink Session Management/Session Reservation/Unreserve Sessions.vi
We need to be careful about the error chaining semantics here. `Unreserve Sessions Impl` will try to perform cleanup regardless of error in state. However, the `Unreserve Callback` implementation does honor error in which could lead to inconsistent state and calling unreserve twice on the session management service during auto cleanup. 

I'm not sure I have a great way to fix this other than to assume that a call to `Unreserve Sessions Impl` always did something meaningful. You could move the call to the callback into the impl, but then we're back to calling the callback while holding the DVR lock. Assuming unreserve always does something meaningful is also somewhat problematic if the user calls Unreserve multiple times since the dispatching in the unreserved state throws an error and doesn't do anything. However, the callback will still be triggered multiple times even though no real work was done outside of the first call. Calling the unreserve callback multiple times is ultimately harmless with the current implementation, but kind of weird conceptually. 

Paul and I have talked about getting rid of the `IState` class in favor of just deleting the DVR and checking whether the refnum is valid rather than dispatching through the `IState` interface. That's something we plan to do eventually, and I think that will help some here. In the meantime, maybe the best we can do is always trigger the callback and have the callback ignore error in as well.

2023-10-18 00:02 UTC, jasonmreding requested changes
Waiting until next round of changes before approving.

2023-10-18 14:27 UTC, pbirkhol-ni approved these changes

2023-10-18 14:27 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Session Management/Session Reservation/Reserve Sessions with Observer.vi
Is the idea to call the Reserve Sessions.vi from within this VI and then all do the callback logic?

2023-10-18 14:27 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Session Management/Session Reservation/Reserve Sessions with Observer.vi
Assuming that you are keeping `Reserve Sessions with Observer.vi`, you should make the observer a required input. In fact, I would consider making this VI community scoped and then making all inputs required. Is there any reason why anyone else would want to call it?

2023-10-18 14:27 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Session Management/IReservationObserver/IReservationObserver.lvclass
I don't have a strong preference for wire color or pattern, but I generally think we should avoid the default red chain. I also don't think we should make it a refnum wire since this interface could technically be implemented by a by-value class. Given those two constraints, I'll let you decide the color and pattern.   :)

2023-10-18 14:27 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Session Management/IReservationObserver/Reserve Callback.vi
This is pretty minor, but I would remove the error case structure on the diagram (same with Unreserve Callback.vi). Since this is an interface method that must be overridden, the contents of the VI don't matter. However, our other interface definitions don't use error case structures. They wire the class input to output and the error input to output, but with no error case structure.

2023-10-18 14:27 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Measurement Server/Classes/MeasurementContext/Reserve Callback.vi
I don't know the best practice here, but I'd prefer naming the class input and output as `measurement context in` and `measurement context out` instead of `reservation observer in` and `reservation observer out`. Same with Unreserve Callback.vi.

2023-10-18 14:35 UTC, jonathanmendez commented on Source/Runtime/MeasurementLink Session Management/Session Reservation/Unreserve Sessions.vi
Here's an attempt to do the "right thing" in the current implementation. Let me know what you think.
![image](https://github.com/ni/measurementlink-labview/assets/7095272/60d660c8-b6fc-49c3-9314-35e53ee2a4f2)
![image](https://github.com/ni/measurementlink-labview/assets/7095272/21ec3254-bf1c-45bc-bf23-e5f60925601b)

Another alternative would be to delegate to the state. I was originally wary of that since the pattern is to call into the state within the DVR, but since the "call the callback" doesn't change the Session Reservation's data, it doesn't have to do that. In that case, the case structure above would be replaced by the call to the state method (with the state passed out of the DVR before the call to Unreserve Impl). The Reserved State implementation would call the callback regardless of incoming error. The Unreserved State would do nothing.

However, given you're thinking of getting rid of the state pattern, I hesitate to use that approach now.

2023-10-18 15:04 UTC, jonathanmendez commented on Source/Runtime/MeasurementLink Session Management/Session Reservation/Reserve Sessions with Observer.vi
I think that the option with least code duplication would be to turn the `main` version of `Reserve Sessions` into `Reserve Sessions with Observer` with the added parameter. Then the new `Reserve Sessions` would just call `Reserve Sessions with Observer` with a default observer instance.

I think of it like having multiple constructors:
```csharp
public SessionReservation(Foo foo, Bar bar) : this(foo, bar, new DefaultObserver()) { }
internal SessionReservation(Foo foo, Bar bar, Observer observer) { /* constructor implementation */ }
```

2023-10-18 18:01 UTC, jasonmreding commented on Source/Runtime/MeasurementLink Session Management/Session Reservation/Unreserve Sessions.vi
I think that's a reasonable solution for now. When we tear out the `IState` class, we can probably rework this some so we're not coupled to that error code by including/excluding the logic as part of the not a refnum check.

2023-10-18 18:13 UTC, jasonmreding approved these changes

2023-10-18 19:18 UTC, merged