Create DMM Example
ni/measurementlink-labview pull request #348
Opened 2023-10-18 04:45 UTC by gpachecoNI

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Creates a NI-DMM example that takes a simple measurement using the new session management APIs/ 

### Why should this Pull Request be merged?

[AB#2533874](https://dev.azure.com/ni/DevCentral/_workitems/edit/2533874/)

### What testing has been done?

Example ran successfully in IS with a simulated device. 
![image](https://github.com/ni/measurementlink-labview/assets/111389775/40128b0f-a2e8-4a94-9c82-0a34f89b23c4)

2023-10-18 15:09 UTC, pbirkhol-ni requested changes

2023-10-18 15:09 UTC, pbirkhol-ni commented on Source/Example Measurements/NI-DMM Measurement/NIDmmMeasurement/Measurement UI.vi
The `Resolution in Digits` control is just a double. However, there are only a handful of valid values. The DMM API uses a ring control to only allow valid values. I would consider making a ring control for the UI to do the same.

2023-10-18 15:10 UTC, pbirkhol-ni commented on Source/Example Measurements/NI-DMM Measurement/README.md
> +This is a MeasurementLink example that acquires a single measurement from a National Instruments DMM.
You should use NI instead of National Instruments.

2023-10-18 15:11 UTC, pbirkhol-ni commented on Source/Example Measurements/NI-DMM Measurement/README.md
> +  - Uses the samse selected measrument function and range for all selected pin/site combinations.
Typoe

2023-10-18 18:23 UTC, jasonmreding approved these changes

2023-10-19 16:51 UTC, gpachecoNI commented on Source/Example Measurements/NI-DMM Measurement/NIDmmMeasurement.lvproj
> +		<Item Name="Build Specifications" Type="Build">
Ok Solved

2023-10-19 18:25 UTC, pbirkhol-ni approved these changes

2023-10-19 18:25 UTC, pbirkhol-ni commented on Source/Example Measurements/NI-DMM Measurement/NIDmmMeasurement/Measurement Logic.vi
We've been adding a timeout of 60000 for the Reserve Sessions.vi.

2023-10-19 19:27 UTC, merged