Adding support to register service on specific  version
ni/measurementlink-labview pull request #349
Opened 2023-10-18 10:25 UTC by svm-ni

### What does this Pull Request accomplish?

Modifying the code to explicitly specify the version of the Measurement Service, which is not supported currently, allows users to register services based on their specific needs, ensuring they can choose the desired service version.

Run Service.vi
![image](https://github.com/ni/measurementlink-labview/assets/147477329/6838db6c-247d-45dc-995b-6a0bcf4c41e2)

![image](https://github.com/ni/measurementlink-labview/assets/147477329/83bd951c-996e-4599-8a9c-3b9e03c14cd7)

### Why should this Pull Request be merged?

By implementing this modification, users can explicitly designate the version of the Measurement Service, a feature not currently supported. This enhancement empowers users to register services according to their unique requirements, enabling them to select the preferred service version.

### What testing has been done?

The existing test cases with respect to the discovery service were executed and they passed.

2023-10-18 15:37 UTC, pbirkhol-ni requested changes

2023-10-18 15:37 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Create Measurement Services.vi
Can you uncheck the `Show as Icon` option for the new control?

2023-10-18 15:37 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Create Measurement Services.vi
I think we can make this slightly more maintainable by removing the case structure that you added. Instead, if the `Measurement Service Version` is empty, create an array with all of the supported services. I've included a screenshot below of what this might look like:
![image](https://github.com/ni/measurementlink-labview/assets/57813166/6d463770-01f8-4914-8e94-c36485797a97)

2023-10-18 15:37 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Create Measurement Services.vi
For the default case, consider throwing an error instead of returning the v2 interface. You could also consider using an enum instead of a string. Then we would be prevented from providing an bad value.

2023-10-18 15:37 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Measurement Server/Run Service.vi
Make sure the front panel of this VI is saved exactly how it was before. This is a user visible VI. This is how I see it after your changes:
![image](https://github.com/ni/measurementlink-labview/assets/57813166/549186fd-94c3-4cff-be18-fc0e34553654)

It should look like this. Notice that there is more space between the bottom of the stop button and the edge of the window.
![image](https://github.com/ni/measurementlink-labview/assets/57813166/281ef436-e2f7-4088-af6a-551a4c6de684)

2023-10-18 15:37 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/TypeDefs/MeasurementLinkServerUserSettings.ctl
The new control should be plural: Measurement Service Version**s**

2023-10-18 15:37 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Measurement Server/Run Service.vi
You should unbundle the Stop Serve and the Measurement Service Versions in the same unbundle node. That will clean up the diagram.

2023-10-18 18:37 UTC, jasonmreding commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Create Measurement Services.vi
FYI, there is also a right click configuration on the case structure to perform case insensitive comparisons which will clean things up a little more. The case structure displays a glyph in the lower left when configured in this mode.

2023-10-18 18:48 UTC, jasonmreding commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/TypeDefs/MeasurementLinkServerUserSettings.ctl
@pbirkhol-ni I can't remember when we added this input terminal, but doesn't this rename break source compatibility of the API? I guess we don't really expect any current customers to have it wired so maybe we're OK with that. However, doesn't this break our test suite?

2023-10-18 18:56 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/TypeDefs/MeasurementLinkServerUserSettings.ctl
Yes, it breaks source compatibility and it breaks our test suite. Since this new input is being added for our test suite, I'm not concerned about that breakage. Sharath will fix it after our next measurementlink-labview release. We considered adding a new input to `Run Service.vi` to not break compatibility for customers, but I am fairly confident that we are the only clients so I am not too concerned with breaking compatibility. You could also make an argument that this input is not an official part of our API; instead, it's a test seam and we won't guarantee compatibility.

2023-10-18 19:21 UTC, jasonmreding commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/TypeDefs/MeasurementLinkServerUserSettings.ctl
I think that's a reasonable position for now. My main concern is that we recognized the test quite breakage and are planning accordingly rather than reacting.

2023-10-18 19:21 UTC, jasonmreding approved these changes

2023-10-19 09:55 UTC, svm-ni commented on Source/Runtime/MeasurementLink Measurement Server/Run Service.vi
Updated the code

2023-10-19 09:59 UTC, svm-ni commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Create Measurement Services.vi
Modified the control to utilize enums instead of strings.

When the array is empty, a constant value is passed, which will register both v1 and v2. If the array is not empty, the appropriate measurement service version case will be applied.

2023-10-19 10:00 UTC, svm-ni commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Create Measurement Services.vi
I've revised the code to utilize enums, ensuring that no invalid values are passed.

2023-10-19 10:01 UTC, svm-ni commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Create Measurement Services.vi
Done

2023-10-19 13:22 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Create Measurement Services.vi
You need to make the enum a typedef. Then replace all instances of the enum with the typedef.

2023-10-19 13:22 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Create Measurement Services.vi
Since you are using an enum now, you can delete the "Default" from the case structure. There should only be two cases: v1 and v2.

2023-10-20 06:52 UTC, svm-ni commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Create Measurement Services.vi
Removed "Default" from case structure

2023-10-20 06:56 UTC, svm-ni commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Create Measurement Services.vi
- Converted Measurement Service Version to typedef and named as **MeasurementServiceVersions.ctl**.
- Added MeasurementServiceVersions.ctl in MeasurementLinkServerUserSettings.ctl.
- Added MeasurementServiceVersions.ctl in front panel of Create Measurement Services.vi
- Added MeasurementServiceVersions.ctl in the block diagram of Create Measurement Services.vi. This will be used when the array is empty.

2023-10-20 19:13 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Measurement Server/Run Service.vi
It looks like you made the changes in all the right places, but you made the wrong thing a typedef. You should make the enum itself a typedef, not the array.

2023-10-20 20:34 UTC, dixonjoel commented
@pbirkhol-ni isn't this a breaking change for existing measurement services? @svm-ni have you tried opening a measurement service created with an older version of the framework with your new changes?

Also, I don't quite understand how the user's supposed to use this feature. Do they show this user settings control on the Run Service.vi front panel and add a specific version to the array if they only want, e.g. V2?

2023-10-20 20:39 UTC, dixonjoel requested changes

2023-10-20 20:39 UTC, dixonjoel commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/TypeDefs/MeasurementServiceVersions.ctl
Most other places use a capital 'V1' and 'V2'. I think 'Version 1' and 'Version 2' would be even clearer, but I'd be ok with either. @pbirkhol-ni what do you think about capitalizing this or changing the 'Version 1'?

2023-10-20 20:57 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/TypeDefs/MeasurementServiceVersions.ctl
I am okay with capital `V1` and capital `V2`. I don't like `Version 1` and `Version 2`.

2023-10-20 21:01 UTC, pbirkhol-ni commented
> @pbirkhol-ni isn't this a breaking change for existing measurement services? @svm-ni have you tried opening a measurement service created with an older version of the framework with your new changes?
> 
> Also, I don't quite understand how the user's supposed to use this feature. Do they show this user settings control on the Run Service.vi front panel and add a specific version to the array if they only want, e.g. V2?

This change is just for enabling testing in our test suite so that we can make sure both V1 and V2 services work. Otherwise, LabVIEW will always advertise both versions and our client will always pick V2. 

I would be surprised if any customers were depending on this input. It is a recommended input, so if you aren't wiring it (and I doubt any customer is since our generator doesn't wire it), then there is no issue. The defaults do the right thing. If you were wiring it, this would break compatibility because of the name change. Since the fix is trivial and I suspect no one is using this feature anyway, I asked Sharath to just modify and rename the existing typedef instead of creating a new one.

2023-10-25 13:59 UTC, svm-ni commented on Source/Runtime/MeasurementLink Measurement Server/Run Service.vi
Made the Enum control as typedef

2023-10-25 14:10 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Create Measurement Services.vi
You should make the `Measurement Service Versions` input a required input.

2023-10-25 14:13 UTC, svm-ni commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Create Measurement Services.vi
Updated the VI

2023-10-25 14:19 UTC, dixonjoel approved these changes

2023-10-25 14:25 UTC, merged