Enable asymmetric init/close behavior
ni/measurementlink-labview pull request #362
Opened 2023-10-21 04:37 UTC by jonathanmendez

- [ ] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md).

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

TODO: Include high-level description of the changes in this pull request.

### Why should this Pull Request be merged?

TODO: Justify why this contribution should be part of the project.

### What testing has been done?

TODO: Detail what testing has been done to ensure this submission meets requirements.

2023-10-24 15:51 UTC, jonathanmendez commented on Source/Runtime/MeasurementLink Session Management/Session Reservation/Create Session.vim
I need to bubble the new parameter up to the driver-specific callers

2023-10-24 16:31 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Instrument/IInstrument/Initialize and Close Session Behavior.ctl
We are not consistent with our use of Initialize and Create. I think this is a larger question. For now, I like using Initialize. Our IInstrument uses Initialize and you could argue that our Create Sessions.vi should be named Initialize Sessions.vi.

2023-10-24 16:35 UTC, bkeryan commented on Source/Runtime/MeasurementLink Instrument/IInstrument/Initialize and Close Session Behavior.ctl
Do you think we should rename create_sessions() to initialize_sessions() in Python as well?

2023-10-24 17:58 UTC, jonathanmendez commented on Source/Runtime/MeasurementLink Session Management/Session Reservation/Create Session.vim
Done

2023-10-24 18:19 UTC, dixonjoel approved these changes

2023-10-24 18:26 UTC, pbirkhol-ni requested changes

2023-10-24 18:26 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Instrument/IInstrument/Session Initialization Details.ctl
I'm not a huge fan of this name. I've been trying to come up with a better name, though, and have drawn a blank. Here are some ideas:
- session initialization options
- session initialization parameters

2023-10-24 18:26 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Session Management/Session Reservation/Create Session.vim
Any reason why the new input shouldn't be required? I realize it could mean updating a lot of tests, but I did that for Get Connections. If we are proposing customers build plugins using this VI, we should get the connector pane right, even if it causes us short term pain. Same comment for Create Sessions.vim.

2023-10-24 18:26 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink niDigital/Instrument/Close MeasurementLink Session.vi
The label on the block diagram is overlapping the control

2023-10-24 19:02 UTC, jonathanmendez commented on Source/Runtime/MeasurementLink Instrument/IInstrument/Close MeasurementLink Session.vi
I don't have a currently existing reason. But just like VISA breaks our abstraction of being able to specify Close behavior at Close time, instead needing it at Init time, I figured maybe some version of the opposite could occur where a 3rd party instrument would need to know how it was initialized in order to decide its Close behavior.

If you would rather defer that until we actually run into a case where we practically need it, I can be convinced of that.

2023-10-24 19:04 UTC, jonathanmendez commented on Source/Runtime/MeasurementLink Instrument/IInstrument/Initialize and Close Session Behavior.ctl
I don't love what it does to the case structures visually, but I agree there's too many of these now.

2023-10-24 19:05 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Instrument/IInstrument/Close MeasurementLink Session.vi
No, I think it is fine. My suggestion below about getting rid of some of the conversion VIs and existing typedefs and handling the cases directly in the implementation VIs might help. I just think we have too many typedefs that mean mostly the same thing.

2023-10-24 19:16 UTC, jonathanmendez commented on Source/Runtime/MeasurementLink Session Management/Session Reservation/Create Session.vim
I guess this is implying:

1. There's no use case for someone to call Create Session(s).vim directly in user code (i.e. where leaving this unwired with the default value would be valuable)
2. We want any plugin that calls this VI to actively wire it rather than allowing a plugin author to leave it unwired for Auto behavior

I guess I don't personally see the value of forcing this to be required when the default behavior is a valid choice. If the idea is to guide a plugin author to push it to their conn pane, to me personally making it required would guide me to think my plugin conn pane should also make it required, which is probably not what we want.

2023-10-24 19:34 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Instrument/IInstrument/Initialize and Close Session Behavior.ctl
I created a work item to change Create to Initialize. AB#2561826

2023-10-24 19:35 UTC, bkeryan commented on Source/Runtime/MeasurementLink Instrument/IInstrument/Initialize and Close Session Behavior.ctl
We discussed this in our status meeting and decided to go ahead with the rename, except for create_nidaqms_task(s).

Python user story: https://dev.azure.com/ni/DevCentral/_workitems/edit/2561827

2023-10-24 20:06 UTC, jonathanmendez commented on Source/Runtime/MeasurementLink Instrument/IInstrument/Initialize and Close Session Behavior.ctl
And for the time being, I updated the typedefs in this PR to use "Initialize" consistently rather than "Create".

2023-10-24 20:10 UTC, jonathanmendez commented on Source/Runtime/MeasurementLink Instrument/IInstrument/To Cleanup Initialize and Close Session Behavior.vi
I added comments to the remaining "To..." VIs.

2023-10-24 20:11 UTC, jonathanmendez commented on Source/Runtime/MeasurementLink Instrument/IInstrument/Close MeasurementLink Session.vi
I implemented the suggestion that removes some of the conversion VIs and typedefs, so I am keeping my current implementation with Close taking the new enum.

2023-10-24 20:13 UTC, jonathanmendez commented on Source/Runtime/MeasurementLink Instrument/IInstrument/Initialize and Close Session Behavior.ctl
Removed the `Initialize Session Behavior.ctl` and `Close Session Behavior.ctl` and their conversion helpers. The case structures are now stretched wide to handle the 4 enum elements. It should hopefully be easier to reason about the controls now with less conversion going on.

2023-10-24 20:13 UTC, jonathanmendez commented on Source/Runtime/MeasurementLink niDigital/Instrument/Close MeasurementLink Session.vi
Fixed.

2023-10-24 20:19 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Session Management/Session Reservation/Create Session.vim
I agree that the default is a valid choice. But it would be easy for us to accidentally forget to wire that input in one of our wrappers, especially when most of our testing happens at the VIM layer and not the API layer. Plugin writers would have the same problem. Making it required at least forces them to think whether they need it or not.

Anyway, I'm a strong proponent of required inputs, so perhaps I'm biased.   :)

2023-10-24 21:19 UTC, jonathanmendez commented on Source/Runtime/MeasurementLink Session Management/Session Reservation/Create Session.vim
I know that @jasonmreding has given similar feedback in the past, so I've deferred and made the input required.

2023-10-24 21:26 UTC, jonathanmendez commented on Source/Runtime/MeasurementLink Instrument/IInstrument/Session Initialization Details.ctl
I like "session initialization parameters" and went with that.

2023-10-25 14:40 UTC, pbirkhol-ni approved these changes

2023-10-25 14:50 UTC, jonathanmendez commented on Source/Runtime/MeasurementLink Instrument/IInstrument/Clean Up MeasurementLink Session for Init Error.vi
Sounds good. Updated.

2023-10-25 15:01 UTC, merged