Limit configuration data types to 32 and 64 bit types
ni/measurementlink-labview pull request #387
Opened 2023-11-03 19:15 UTC by dixonjoel

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

grpc-labview has [an issue](https://github.com/ni/grpc-labview/issues/323) where it incorrectly serializes Int16 (or Int8) data. Leads to various problems but AB#2562693 represents one. This PR limits the data types in the configuration cluster to 32 and 64 bit numeric types. When a LabVIEW service is run, the user will see an error like this.
![image](https://github.com/ni/measurementlink-labview/assets/38357562/3488f5cb-db84-4990-aae3-cb6d93ee63fc)

It turns out that we were already advertising only 32 and 64 bit support. This enforces that in the measurement service
https://www.ni.com/docs/en-US/bundle/measurementlink/page/supported-datatypes.html

### Why should this Pull Request be merged?

Prevent confusion and strange errors in the default values and other places of the measurement service.

### What testing has been done?

Built the packages and ran the measurement service attached to AB#2562693.

2023-11-03 19:17 UTC, dixonjoel commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Validate Configuration Metadata.vi
New data type checking.
![image](https://github.com/ni/measurementlink-labview/assets/38357562/78c8deb9-0151-4ba6-a6c7-d627a8c45a12)

2023-11-03 19:18 UTC, dixonjoel commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/LabVIEW datatype to Measurement datatype.vi
Took out the 8 and 16 bit types in the cases.
![image](https://github.com/ni/measurementlink-labview/assets/38357562/a3486ff9-d9eb-4401-9add-6184c34ce652)

2023-11-03 22:48 UTC, jasonmreding commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/LabVIEW datatype to Measurement datatype.vi
What about enums of sizes other than 32 bits? I believe the protobuf spec only supports encoding as 32 bits. Does this have the same issue? I see there is still a "Enum U64". I don't know if the original list also had the U8 and U16 versions of enums and you just forgot to remove support for this variation.

2023-11-03 22:55 UTC, jasonmreding commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/LabVIEW datatype to Measurement datatype.vi
There is also some code in the gplugin used to host the LV UI for the service which includes mappings for these types. Now that the service will fail to start because of this condition, this should more or less be dead code. Are you planning to update that code as well to avoid confusion?

2023-11-03 22:55 UTC, jasonmreding approved these changes

2023-11-05 18:55 UTC, dixonjoel commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/LabVIEW datatype to Measurement datatype.vi
> I don't know if the original list also had the U8 and U16 versions of enums and you just forgot to remove support for this variation.

Yes, the list had Enum U8 and Enum U16. I didn't think about Enum U64, but it seems like you're right. I should take that out as well.

2023-11-05 19:04 UTC, dixonjoel commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/LabVIEW datatype to Measurement datatype.vi
Hmm LabVIEW 2020 SP1 doesn't even let me select U64 for an enum. Guess we should axe that.
![image](https://github.com/ni/measurementlink-labview/assets/38357562/af6c3788-a1e5-4bf3-9ea4-bf6edec0c8db)

2023-11-06 14:47 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/LabVIEW datatype to Measurement datatype.vi
If you implement my comment below, you won't need the subVI because we will only throw this error in a single place.

2023-11-06 14:48 UTC, pbirkhol-ni requested changes
Ignore this comment. Github wouldn't let me post my review without it.

2023-11-06 16:58 UTC, dixonjoel commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Validate Configuration Metadata.vi
Renamed this to Validate Metadata since it's used for results as well. Removed the error handling from Get Metadata*

2023-11-06 17:10 UTC, dixonjoel commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/LabVIEW datatype to Measurement datatype.vi
Keeping Enum 64. I'll update the 'LabVIEW DataType to Parameter Type.vi' in a separate PR.

2023-11-06 21:36 UTC, pbirkhol-ni approved these changes

2023-11-06 21:36 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Get Parameters And Check Data Types.vi
This could all be replaced with an indexing terminal at the output of the loop, right? I know this is existing code, but it is very confusingly doing a simple thing.

![image](https://github.com/ni/measurementlink-labview/assets/57813166/18442f42-e212-40d0-845c-84b099986b8f)

2023-11-06 21:36 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/Get Parameters And Check Data Types.vi
Make sure the input is required and the control indicator names are all lower case.

2023-11-06 22:46 UTC, merged

2023-11-07 16:11 UTC, jasonmreding commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/LabVIEW datatype to Measurement datatype.vi
I'm a little confused by the tail end of this thread. LV may support a 64 bit enum, but gRPC never will, right? That was the whole point of removing the other enum types to begin with.

2023-11-07 17:51 UTC, dixonjoel commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/LabVIEW datatype to Measurement datatype.vi
@pbirkhol-ni based on this, should I go ahead and remove it with another PR?

2023-11-07 17:56 UTC, pbirkhol-ni commented on Source/Runtime/MeasurementLink Measurement Server/Helpers/LabVIEW datatype to Measurement datatype.vi
Yes, you can make the change. I didn't know that grpc enums are always 32bit, but just confirmed in the spec.
`Enumerator constants must be in the range of a 32-bit integer.`
https://protobuf.dev/programming-guides/proto3/#enum