Include Port number in LabVIEWCLI in run_tests.py
ni/measurementlink-labview pull request #411
Opened 2023-11-17 09:53 UTC by MounikaBattu17

- [ ] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?
- Currently in `run_tests.py`, `LabVIEWCLI` has `-OperationName` (required) and `-LabVIEWPath` {optional) arguments.
- For working with multiple LabVIEW versions with unique TCP/IP Port numbers, `LabVIEWCLI` requires yet another argument `-PortNumber` to communicate with LabVIEW.
- Thus, added  optional argument `--port_number` and passed the same to the `LabVIEWCLI` with default value `3363`.

### Why should this Pull Request be merged?
measlinkbot labview runner requires this change to run tests in multiple LabVIEW versions.

### What testing has been done?
Ran the following command and ensured connection is established with LabVIEW.
```
PS D:\measurementlink-labview\Source\Tests> python run_tests.py --labview_path "C:\Program Files\National Instruments\LabVIEW 2020\LabVIEW.exe" --port_number "3365"
Launching D:\measurementlink-labview\Source\Tests\run_tests.vi.
LabVIEWCLI started logging in file:  C:\Users\battu.mounika\AppData\Local\Temp\lvtemporary_96279.log
Using LabVIEW: "C:\Program Files\National Instruments\LabVIEW 2020\LabVIEW.exe"
LabVIEW launched successfully.
Connection established with LabVIEW at port number 3365.
```

2023-11-17 10:23 UTC, keer1111 approved these changes

2023-11-17 10:38 UTC, vigkre approved these changes

2023-11-17 15:43 UTC, bkeryan requested changes

2023-11-17 15:43 UTC, bkeryan commented on Source/Tests/run_tests.py
> +    parser.add_argument("--port_number", type=str, help="TCP/IP port number of LabVIEW executable", nargs='?', default="3363")
Command line parameters should use kebab-case. The argparse module will automatically convert these to snake_case in the args object.

2023-11-17 15:43 UTC, bkeryan commented on Source/Tests/run_tests.py
> +    parser.add_argument("--port_number", type=str, help="TCP/IP port number of LabVIEW executable", nargs='?', default="3363")
Port numbers are numbers, not strings.

(FYI, some MeasurementLink code uses a string for the port in order to leave the door open to UNIX domain sockets, but that doesn't apply here.)

2023-11-17 15:45 UTC, bkeryan commented on Source/Tests/run_tests.py
> +        kwargs.extend(["-LabVIEWPath", labview_path, "-PortNumber", port_number])
This ignores the port number if you didn't specify the LabVIEW path.

2023-11-18 16:11 UTC, bkeryan approved these changes

2023-11-18 16:37 UTC, merged