Skip VISA tests for LV 2020
ni/measurementlink-labview pull request #434
Opened 2023-12-06 08:26 UTC by MounikaBattu17

- [ ] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?
VISA tests uses VISA 2024 Q1 which doesn't support LabVIEW 2020. Thus skipping the VISA tests for LV 2020 seems to be the right thing do. So I have made the following changes in `run_tests.vi`.
- The VISA tests are identified in the basis of "`VISA`" string in test name.
- I have used Application Version property node and matched pattern with string `20.0` to find the LV version on which the VI is running.
- Added a case structure to search for `VISA` in the test case name.
- Finally, `AND` gate to validate the resulting booleans and skip tests. So the tests will be skipped if either they are added in `skip_tests.lst `or the test name contains VISA when running in LV 2020.
Here's the diff of old and new run_tests.vi
![image](https://github.com/ni/measurementlink-labview/assets/126869186/672cb4f7-ac9e-4dcd-94fa-519d86b19a5f)
![new](https://github.com/ni/measurementlink-labview/assets/126869186/b198dfee-ac62-4315-b3a5-5958595c8da9)

### Why should this Pull Request be merged?
Running VISA tests in LV 2020 requires manually copy pasting VISA VIs to LV 2020 vi.lib folder. So eliminating VISA tests for LV 2020 is ideal. Also, upcoming measlinkbot has higher LV versions where VISA tests could be run.

### What testing has been done?
Ran `run_tests.vi` in LV 2020 & LV 2023 and observed VISA tests are skipped for only LV 2020.

2023-12-06 14:38 UTC, dixonjoel approved these changes

2023-12-06 14:39 UTC, pbirkhol-ni commented on Source/Tests/run_tests.vi
You should make the version regex 20\.0 so that it only matches 20.0. As is, the . will match any character.

2023-12-06 14:45 UTC, pbirkhol-ni commented on Source/Tests/run_tests.vi
Skipping these tests is fine, but not until we have a test runner that uses a different version of LabVIEW. As far as I know, we only have `spawningpool`, which only runs tests on LabVIEW 2020. If we have other test runners, we should add them to the PR build before submitting this PR. If we don't have other test runners, we should hold off on submitting this PR.

2023-12-06 14:45 UTC, pbirkhol-ni commented on Source/Tests/run_tests.vi
Looking for `VISA` in the test name is probably too fragile for a long term solution. However, I anticipate that we'll be upgrading the minimum LabVIEW version to 2021 in the near future so this should be okay for now. We have considered splitting our tests into more libraries, which could make this type of filtering easier. Anyway, no action item for this PR.

2023-12-06 14:46 UTC, pbirkhol-ni requested changes
See comments for requested changes.

2023-12-06 16:36 UTC, dixonjoel commented on Source/Tests/run_tests.vi
If spawningpool is running the tests on LV 2020, are they passing now? I'm confused.

2023-12-06 16:41 UTC, MounikaBattu17 commented on Source/Tests/run_tests.vi
Some VISA VIs are manually copy pasted in spawningpool to run tests in LV 2020. That's why the VISA tests are passing in spawningpool.

2023-12-06 17:02 UTC, MounikaBattu17 commented on Source/Tests/run_tests.vi
>If we have other test runners, we should add them to the PR build before submitting this PR. If we don't have other test runners, we should hold off on submitting this PR.

@pbirkhol-ni Currently PRs are ongoing for measlinkbot which has LV 2020, 2021, 2022, 2023. So once the PRs are approved, measlinkbot with labview setup can be deployed to AWS and the same can be hosted as a runner here. The issue in holding this PR until the above steps happen is that we run tests as a part of build stage of measlinkbot, so currently the LV 2020 VISA tests are failing in the build stage. Without this change the build stage of measlinkbot cannot succeed. There are few shortcuts that can be made for the measlinkbot build stage to succeed.
1) We can copy paste the VIs manually in measlinkbot also
2) Currently, the tests are running from main branch source code, instead we can change the target branch to this branch and run tests.

Note: These changes can only be temporary and should be reverted back once the runner is set up here.

Please share your thoughts.

2023-12-07 16:41 UTC, pbirkhol-ni commented on Source/Tests/run_tests.vi
You're change looks reasonable. However, I'd rather the logic be something like this:
```
if 20.0 and not spawningpool:
    if not VISA:
        run test
```

After you make that change, go ahead and submit.

2023-12-07 19:22 UTC, merged