Add VI option to the game of life example.
ni/measurementlink-labview pull request #448
Opened 2023-12-08 20:18 UTC by gpachecoNI

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md). _(Required)_
- [x]  Automatically post PR comments with images for G code changes? _(Recommended for small changes)_

### What does this Pull Request accomplish?

Includes VI cases for the Game Of Life example.

### Why should this Pull Request be merged?

AB [#2475641](https://dev.azure.com/ni/DevCentral/_workitems/edit/2575641/)

### What testing has been done?

Run the example with the VI option:
![image](https://github.com/ni/measurementlink-labview/assets/111389775/70c1d9a2-a7fd-42a9-96bb-efceff3f8b71)

2023-12-08 21:21 UTC, pbirkhol-ni requested changes
Make sure you build an exe. I think that will fail until you rename the UI VI.

2023-12-08 21:21 UTC, pbirkhol-ni commented on Source/Example Measurements/Game Of Life/Game Of Life.lvlib/GameOfLife.vi
Consider naming this `Measurement UI.vi` so that it matches our other examples.

2023-12-08 21:21 UTC, pbirkhol-ni commented on Source/Example Measurements/Game Of Life/Game Of Life.lvlib/GameOfLife.vi
You need to add this VI to the library.

2023-12-08 21:21 UTC, pbirkhol-ni commented on Source/Example Measurements/Game Of Life/Game Of Life.lvlib/Get UI Details.vi
My preference would be to make the VI the default. In fact, I think I'd prefer deleting the .measui entirely, but it might be valuable to keep around until your changes to the GPlugin are in a build.

2023-12-09 00:48 UTC, jasonmreding commented on Source/Example Measurements/Game Of Life/Game Of Life.lvlib/GameOfLife.vi
It should at least use book casing to match naming style for all the other VI file names. I have a rename in flight for UI -> User Interface. Example consistency is probably preferable at this point. However, we might want to consider renaming this in all our examples for consistency with the class member name once my rename PR is checked in.

2023-12-09 00:51 UTC, jasonmreding commented on Source/Example Measurements/Game Of Life/Game Of Life.lvlib/Get UI Details.vi
This will conflict with the rename PR I'm about to submit. The VI name will be renamed to `Get User Interface Details.vi`. I have a script that does the retrofit so it shouldn't be too hard to reconcile things if this PR gets submitted first.

2023-12-11 17:13 UTC, jasonmreding commented on Source/Example Measurements/Game Of Life/Game Of Life.lvlib/Get UI Details.vi
This is the PR that will cause conflicts.

https://github.com/ni/measurementlink-labview/pull/450

2023-12-13 00:48 UTC, gpachecoNI commented on Source/Example Measurements/Game Of Life/Game Of Life.lvlib/Get UI Details.vi
Something happened because I dont see the update... Are you sure you change it? I will do it myself.

2023-12-13 00:49 UTC, gpachecoNI commented on Source/Example Measurements/Game Of Life/Game Of Life.lvlib/Get UI Details.vi
OK

2023-12-13 17:20 UTC, dixonjoel commented on Source/Example Measurements/Game Of Life/Game Of Life.lvlib/Get UI Details.vi
I'd like to list the .vi first since this is a LabVIEW example.

2023-12-13 17:20 UTC, dixonjoel commented on Source/Example Measurements/Game Of Life/Game Of Life.lvlib/Get UI Details.vi
Agree as mentioned in another comment.

2023-12-14 01:22 UTC, gpachecoNI commented on Source/Example Measurements/Game Of Life/Game Of Life.lvlib/Get UI Details.vi
None of the other example had the updated name. So I kept for now the name file to match other examples.

2023-12-14 19:31 UTC, pbirkhol-ni commented on Source/Example Measurements/Game Of Life/Game Of Life.lvlib/Measurement UI.vi
You need to make this part of the Game of Life library.

2023-12-14 19:31 UTC, pbirkhol-ni approved these changes

2023-12-15 17:29 UTC, merged