Internal - Pin group support in MeasurementLink LabVIEW Client API
ni/measurementlink-labview pull request #492
Opened 2024-03-06 11:20 UTC by Prem-MysteryPro

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md). _(Required)_
- [ ]  Automatically post PR comments with images for G code changes? _(Recommended for small changes)_

### What does this Pull Request accomplish?

* Certain pins can be grouped in a pin map based on the user's need. Hence, the `LabVIEW MeasurementLink client` supports the reservation of a group of pins by giving the pin group name instead of providing all the pins manually.
* The `LabVIEW MeasurementLink client API` also supports getting the connection information for the given pin group name.
* This PR doesn't contain the changes on the examples, but few tests are created to validate the pin group support.

### Why should this Pull Request be merged?

* To support the pin group input to get the connection reservation and connection information in LabVIEW measurements.

### What testing has been done?

* The existing 151 tests are passed locally.
* 7 new tests are added to validate the pin group feature.

![image](https://github.com/ni/measurementlink-labview/assets/108566201/10acff7e-8ad4-4821-aad5-fe8229039715)

2024-03-06 12:02 UTC, Prem-MysteryPro commented
@dixonjoel @jasonmreding,
I believe that the newly written `test_ReserveSessionForPinGroup_ReceiveGroupMappingInformation.vi` is failing in the server alone since the `Spawning Pool` is not updated with the latest MeasurementLink (installer version 24.3.0.296+d296).

2024-03-06 16:09 UTC, dixonjoel commented
> @dixonjoel @jasonmreding, I believe that the newly written `test_ReserveSessionForPinGroup_ReceiveGroupMappingInformation.vi` is failing in the server alone since the `Spawning Pool` is not updated with the latest MeasurementLink (installer version 24.3.0.296+d296).

Passed in the latest run. Spawningpool is updated.

2024-03-06 17:11 UTC, dixonjoel requested changes
I'll wait to see the next pass when the front panels are cleaned up.

2024-03-06 17:37 UTC, jasonmreding requested changes

2024-03-06 17:37 UTC, jasonmreding commented on Source/Tests/Tests.Runtime/Measurement Server/Get Connections/test_OneSessOnePinGroupOneInstrOneSiteReservation_CallNiDcPowerGetConnections1PinMConnections_ReturnsTwoConnections.vi
Consider moving this file and the other test file into a virtual folder "Pin Groups" for better organization of the different functional areas being tested.

2024-03-06 17:37 UTC, jasonmreding commented on Source/Tests/Tests.Runtime/Session Management Client/test_ReserveSessionForPinGroupAndPinInSameGroup_ReserveSuccessForNonDuplicatePins.vi
The tests in this area are basically meant to serve as sanity tests when regenerating the client stubs from grpc-labview. They usually perform communication with the server and do some basic sanity checking that communication with the server is happening correctly via the client stub. 

Because of this, the number of tests in this area are typically kept to a minimum. Otherwise, you're effectively testing functionality of the server, and we already have tests that do that (typically in the C# code since these are C# services). Given that, I think it would be better to remove most/all of these tests or move them to the `Measurement Server` project under the `Session Reservation Tests` library.

![image](https://github.com/ni/measurementlink-labview/assets/103200169/b17700bb-114a-4d9b-8912-94ed1321fa33)

There is better test infrastructure at this level that should make the tests easier to write and read.

2024-03-06 17:42 UTC, jasonmreding commented on Source/Runtime/MeasurementLink Session Management V1/Session Reservation/Reserve Registered Sessions.vi
This is a public API and we shouldn't be changing its conn pane in this fashion. The connector pane layout was done this way so that it matches the other public API, `Reserve Sessions`. 

![image](https://github.com/ni/measurementlink-labview/assets/103200169/4480740b-9e80-46fc-b2be-b421650169f3)

2024-03-06 18:20 UTC, dixonjoel commented on Source/Runtime/MeasurementLink Session Management V1/Session Reservation/Reserve Registered Sessions.vi
Ah, didn't think about that. Thanks @jasonmreding

2024-03-07 05:05 UTC, Prem-MysteryPro commented
> > @dixonjoel @jasonmreding, I believe that the newly written `test_ReserveSessionForPinGroup_ReceiveGroupMappingInformation.vi` is failing in the server alone since the `Spawning Pool` is not updated with the latest MeasurementLink (installer version 24.3.0.296+d296).
> 
> Passed in the latest run. Spawningpool is updated.

Thank you for updating the `SpawningPool`

2024-03-07 09:06 UTC, Prem-MysteryPro commented on Source/Runtime/MeasurementLink Session Management V1/Session Reservation/Reserve Sessions Wrapper.vi
Being a new developer to the team I was a little over-excited and added decorations 😅. I agree and I have removed the unnecessary decorators and labels. I will make sure to follow this standard. Just used `Ctrl + U` to clean up the controls.

2024-03-07 09:07 UTC, Prem-MysteryPro commented on Source/Runtime/MeasurementLink Session Management V1/Session Reservation/Reserve Registered Sessions.vi
Thanks for the recommendations. I just did `ctrl + U` to organize the controls and maintain consistency otherwise I didn't change the connector pane as recommended.

2024-03-07 09:09 UTC, Prem-MysteryPro commented on Source/Runtime/MeasurementLink Session Management V1/Session Reservation/Create Session Reservation.vi
Thanks for pointing this. I have made `session reservation response` as required input.

2024-03-07 09:16 UTC, Prem-MysteryPro commented on Source/Runtime/MeasurementLink Session Management V1/Session Reservation/Get Connections Impl.vi
Ah yes! Sure, Jason. I have changed the description and followed the same.

![image](https://github.com/ni/measurementlink-labview/assets/108566201/86dd9ff0-6902-460d-a9a2-75bc5c6c45c0)

2024-03-07 09:21 UTC, Prem-MysteryPro commented on Source/Runtime/MeasurementLink Session Management V1/Session Reservation/Resolve To Pins from Group.vi
Thanks for the suggested name. I have changed from `pin or relay or its group names` terminal name to `pin or group names`.

2024-03-07 09:22 UTC, Prem-MysteryPro commented on Source/Runtime/MeasurementLink Session Management V1/Session Reservation/Resolve To Pins from Group.vi
Sure, changed the vi name to `Resolve Pin Groups to Pins.vi`

2024-03-07 09:25 UTC, Prem-MysteryPro commented on Source/Runtime/MeasurementLink Session Management V1/Session Reservation/Reserve Sessions Wrapper.vi
Sure, I reverted to the old state without documentation and with organized front panel control.

2024-03-07 09:27 UTC, Prem-MysteryPro commented on Source/Runtime/MeasurementLink Session Management V1/Session Reservation/Group Mapping.ctl
I did the `Apply Icon To VIs` yes it did affect all the files under the class. I just saved those who didn't have the proper Icon before.

2024-03-07 09:36 UTC, Prem-MysteryPro commented on Source/Tests/Tests.Runtime/Measurement Server/Get Connections/test_OneSessOnePinGroupOneInstrOneSiteReservation_CallNiDcPowerGetConnections1PinMConnections_ReturnsTwoConnections.vi
Done.
![image](https://github.com/ni/measurementlink-labview/assets/108566201/1b7cf00b-a197-45b7-8d6b-978d694897b7)

2024-03-07 09:43 UTC, Prem-MysteryPro commented on Source/Tests/Tests.Runtime/Session Management Client/test_ReserveSessionForPinGroupAndPinInSameGroup_ReserveSuccessForNonDuplicatePins.vi
I completely understand. I wrote the most possible test cases and there are 5 new test cases regarding `session reservation`. These test cases gave a clue the new session response from the server was not coming to LV client side and that the `spawningpool` requires an update of the latest `MeasurementLink`. So, I feel like moving them under `Session Reservation Tests.lvlib` rather than removing them. I have moved them as suggested. Kindly let me know if you want to remove them instead.

2024-03-07 14:36 UTC, Prem-MysteryPro commented on Source/Runtime/MeasurementLink Session Management V1/Session Reservation/Resolve To Pins from Group.vi
@jasonmreding 
For now, I have used insert into array as an alternative. Kindly let me know if this is fine.

![image](https://github.com/ni/measurementlink-labview/assets/108566201/3cf11c59-12f7-4c19-a9dd-f2c52177a76f)

2024-03-07 17:29 UTC, jasonmreding commented on Source/Runtime/MeasurementLink Session Management V1/Session Reservation/Resolve To Pins from Group.vi
I think using `Initialize Array` would be more readable and make more sense for this case. 

![image](https://github.com/ni/measurementlink-labview/assets/103200169/c85fc36d-fca4-444e-85a7-1d6b87de5b2c)

The terminal wired to the empty string constant above should be wired to the loop tunnel instead though. I don't know enough about the VI Analyzer configuration settings to know if this is something that can be tuned. It's probably not worth the effort for this one issue.

2024-03-07 17:34 UTC, dixonjoel approved these changes

2024-03-07 17:45 UTC, jasonmreding commented on Source/Tests/Tests.Runtime/Measurement Server/Session Management/Session Reservation/TestAssets/PinGroupSupport-NIDCPowerSourceDCVoltage.pinmap
Please add this file to the LV project as well like so:

![image](https://github.com/ni/measurementlink-labview/assets/103200169/f0bb9423-2d3a-442e-816a-6ac5b96853c7)

You can't use auto populating folders inside of a library in LV so we'll have to live with virtual folders that we maintain by hand.

2024-03-07 17:55 UTC, jasonmreding commented on Source/Tests/Tests.Runtime/Measurement Server/Session Management/Session Reservation/test_ReserveSessionForPinGroupAndPinInSameGroup_ReserveSuccessForNonDuplicatePins.vi
These tests should be rewritten to use the higher level APIs that are provided via the library this test library is meant to test. See other examples of tests in this library. If there are tests you feel are redundant with existing tests at this level, feel free to delete them.

2024-03-07 17:59 UTC, jasonmreding commented on Source/Tests/Tests.Runtime/Measurement Server/Session Management/Session Reservation/test_ReserveSessionForPinGroupAndPinInSameGroup_ReserveSuccessForNonDuplicatePins.vi
For the reworked tests that you keep, be sure that any block diagram constants are expanded so that all relevant data for the test is is visible. For string constants, ensure the strings are fully visible and can be read without having to use tool tips or expanding the constant. For arrays, ensure all elements of the array are visible.

2024-03-07 19:03 UTC, jasonmreding commented on Source/Tests/Tests.Runtime/Measurement Server/Session Management/Session Reservation/test_ReserveSessionForPinGroupAndPinInSameGroup_ReserveSuccessForNonDuplicatePins.vi
Please rename tests as follows to better follow given_when_then conventions and improve readability:
- test_Pin_ReserveSessions_EmptyGroupMappings.vi
- test_PinGroup_ReserveSessions_GroupMappingsContainsPinGroup.vi
- test_PinGroup_ReserveSessions_ChannelMappingsContainsAllPinsFromPinGroup.vi
- test_PinAndPinGroup_ReserveSessions_ChannelMappingsContainsPinsFromBoth.vi
- test_PinAndPinGroupContainingSamePin_ReserveSessions_ChannelMappingsDoesNotContainDuplicatePins.vi

2024-03-07 19:16 UTC, dixonjoel commented on Source/Tests/Tests.Runtime/Measurement Server/Session Management/Session Reservation/test_ReserveSessionForPinGroupAndPinInSameGroup_ReserveSuccessForNonDuplicatePins.vi
Thanks for saying this. The test names are getting kind of comically long.

2024-03-08 14:03 UTC, Prem-MysteryPro commented on Source/Runtime/MeasurementLink Session Management V1/Session Reservation/Resolve To Pins from Group.vi
Agreed! I have changed it to `initialize array`.

![image](https://github.com/ni/measurementlink-labview/assets/108566201/66c86a24-4469-4c31-82f3-8e96882dc1f6)

2024-03-08 14:08 UTC, Prem-MysteryPro commented on Source/Tests/Tests.Runtime/Measurement Server/Session Management/Session Reservation/TestAssets/PinGroupSupport-NIDCPowerSourceDCVoltage.pinmap
Got it. I have added the corresponding virtual folder. I will make sure to maintain proper virtual folders for the files added to libraries or projects.

![image](https://github.com/ni/measurementlink-labview/assets/108566201/878298fd-36b7-4e16-9925-dcd3150a1547)

2024-03-08 14:14 UTC, Prem-MysteryPro commented on Source/Tests/Tests.Runtime/Measurement Server/Session Management/Session Reservation/test_ReserveSessionForPinGroupAndPinInSameGroup_ReserveSuccessForNonDuplicatePins.vi
Referred to the other similar tests and rewrote with high-level API's. Removed two tests I wrote since those test cases will be already verified in other test cases and were redundant. Please find the high-level API's I used to rewrite the tests.

![image](https://github.com/ni/measurementlink-labview/assets/108566201/6fd99859-2cec-48be-b415-90c2b2512c96)

2024-03-08 14:23 UTC, Prem-MysteryPro commented on Source/Tests/Tests.Runtime/Measurement Server/Session Management/Session Reservation/test_ReserveSessionForPinGroupAndPinInSameGroup_ReserveSuccessForNonDuplicatePins.vi
Sure, verified the modified tests. Expanded the text and array for complete visibility.
I also expanded the constants to complete visibility in the `GetConnections` test that I wrote.

![image](https://github.com/ni/measurementlink-labview/assets/108566201/9f58369d-9a15-45d9-8e3c-24c4ac4fc1fc)

![image](https://github.com/ni/measurementlink-labview/assets/108566201/29ab6be3-d193-4c02-b8f1-b015fb0fe191)

2024-03-08 14:26 UTC, Prem-MysteryPro commented on Source/Tests/Tests.Runtime/Measurement Server/Session Management/Session Reservation/test_ReserveSessionForPinGroupAndPinInSameGroup_ReserveSuccessForNonDuplicatePins.vi
@jasonmreding 
Thanks a lot for the time in reviewing and providing the name suggestions. I have to improve a lot on naming.
I have renamed the tests to the suggested names.

2024-03-08 14:45 UTC, Prem-MysteryPro commented
@jasonmreding @dixonjoel 
I'm not sure what to do with the comments that `Github actions` have left. Should I simply click resolve for the `Github actions` Comments after your approval? Kindly guide me on this.

2024-03-08 14:47 UTC, dixonjoel commented
> @jasonmreding @dixonjoel I'm not sure what to do with the comments that `Github actions` have left. Should I simply click resolve for the `Github actions` Comments after your approval? Kindly guide me on this.

Yes, for the comments related to diff images, you can just resolve them before submitting.

2024-03-08 17:51 UTC, jasonmreding commented on Source/Tests/Tests.Runtime/Measurement Server/Session Management/Session Reservation/test_PinAndPinGroupContainingSamePin_ReserveSessions_ChannelMappingsDoesNotContainDuplicatePins.vi
Rather than using the private client wrapper VIs, use the public APIs from the library instead. This should clean up the test VIs quite a bit. You can use the `Get Session Info.vi` to access the session information from the reservation class.

For tests that need to access the group mappings, I would recommend doing something similar. However, there isn't currently an accessor API for getting the group mappings so I would add one. If you don't want to bother with making this a public API, you can just add it at community scope under the `Test Helpers` folder in the project. Otherwise just make it public and documentation and an appropriate icon. If there are reasonable use cases where the user might have a need to access the group mappings directly, then it should be public. In general, I would lean more towards making it public than not. The only reason not to is coming up with a reasonable icon can be a pain.

2024-03-08 17:56 UTC, jasonmreding commented on Source/Tests/Tests.Runtime/Measurement Server/Session Management/Session Reservation/test_PinAndPinGroupContainingSamePin_ReserveSessions_ChannelMappingsDoesNotContainDuplicatePins.vi
There is a map collection glyph in the existing glyph library which might be as good as anything else.

![image](https://github.com/ni/measurementlink-labview/assets/103200169/ecb80d81-3372-45da-9801-9e811a695db8)

This is starting from the icon from `Get Session Info - 1Sess .vi` and replacing the document looking icon with this one from the glyph library when searching for "map".

2024-03-08 17:59 UTC, jasonmreding approved these changes

2024-03-09 07:58 UTC, Prem-MysteryPro commented on Source/Tests/Tests.Runtime/Measurement Server/Session Management/Session Reservation/test_PinAndPinGroupContainingSamePin_ReserveSessions_ChannelMappingsDoesNotContainDuplicatePins.vi
I used the `community scope` wrapper `Reserve Sessions Wrapper.vi` in tests since I thought the `session reservation` attributes were private. I probably should have looked the accessors once. Now I have used the public API's in the tests rather using the `community scope` wrapper.
![image](https://github.com/ni/measurementlink-labview/assets/108566201/51c2399d-dd60-4adb-b9ac-c827205b42ea)

Thanks for pointing out the public accessor. I believe that the `group mapping` information will be useful for the user at some point while debugging or to log it. I have created a public accessor for getting the `group mapping` and used it in the tests.
![image](https://github.com/ni/measurementlink-labview/assets/108566201/e1e51775-f23a-4d80-8853-730e772cdd68)

I have edited the Icon as suggested. Thanks for the suggestion.

![image](https://github.com/ni/measurementlink-labview/assets/108566201/b52b6806-61f1-40a4-8e43-1ec239816ea3)

2024-03-11 11:48 UTC, Prem-MysteryPro commented on Source/Tests/Tests.Runtime/Measurement Server/Session Management/Session Reservation/test_PinAndPinGroupContainingSamePin_ReserveSessions_ChannelMappingsDoesNotContainDuplicatePins.vi
@jasonmreding 
I hope the above changes are fine. Shall I proceed with resolving the `GitHub bot` comments and merge the changes?

2024-03-11 16:03 UTC, jasonmreding commented on Source/Tests/Tests.Runtime/Measurement Server/Session Management/Session Reservation/test_PinAndPinGroupContainingSamePin_ReserveSessions_ChannelMappingsDoesNotContainDuplicatePins.vi
I am good with the current state of the PR. I was going to say we should probably update the palette file for the class so it includes the new public getter for the group mappings. However, then I realized we didn't actually include `Get Session Info.vi` in the palette. I'm not sure why we did that. I'm guessing it was just an oversight. You are welcome to make that change as part of this PR as well if you like. Otherwise, we can do that in a future PR.

2024-03-11 17:16 UTC, Prem-MysteryPro commented on Source/Tests/Tests.Runtime/Measurement Server/Session Management/Session Reservation/test_PinAndPinGroupContainingSamePin_ReserveSessions_ChannelMappingsDoesNotContainDuplicatePins.vi
Sure, we can include them as part of this PR. However, I haven't had any experience with palette editing in the code base yet. Kindly educate me on the following.
I am guessing I should use `Tools»Advanced»Edit Palette Set` dialog and synchronize with `Session Reservation.mnu` file and add the two vi's. Kindly correct me if I'm wrong.
Probably here as the last two, 
![2024-03-11_22h39_59](https://github.com/ni/measurementlink-labview/assets/108566201/0dfb0884-ba3c-42b7-8eff-e43f8bd168a9)

Any suggestions on the order? I wonder if it would be better if we add it before the instrument-specific sub palette. But there would be some irregularity in the row anyway.

2024-03-11 18:18 UTC, jasonmreding commented on Source/Tests/Tests.Runtime/Measurement Server/Session Management/Session Reservation/test_PinAndPinGroupContainingSamePin_ReserveSessions_ChannelMappingsDoesNotContainDuplicatePins.vi
Editing palettes is a pain. Yes, using the tools menu to edit palettes is typically the way to go. I would recommend doing some searches on editing palettes in LV if you aren't able to figure it out on your own. I think you will end up having to copy files around on disk though since I believe LV always stores the edited palettes in a fixed location that won't match our source control layout.

As far as suggestions on order, it's pretty subjective and hard to say until you can see the proposed layout. When possible, I like the palette layout to match the typical order VIs would be dropped when using the API. My initial thoughts are:
1. Just create a second row (keep driver sub palettes on the third row), and put the two getter APIs on the second row. This is the least disruptive assuming it doesn't look too weird.
2. Move Reserve Registered, Register, and Unregister VIs to the second row. Add two new getter APIs where they were on the first row and collapse everything down towards the left. These APIs will typically be used by code modules and not as part of the measurement logic so having them grouped together on their own row might make sense.

2024-03-11 18:28 UTC, Prem-MysteryPro commented on Source/Tests/Tests.Runtime/Measurement Server/Session Management/Session Reservation/test_PinAndPinGroupContainingSamePin_ReserveSessions_ChannelMappingsDoesNotContainDuplicatePins.vi
Got it. Thanks a lot for the detailed explanation. I will note this down and convey the same to the team just in case if someone else in the future works on the palette editing. Probably we will add `Tech Debt` to this.
For now, I will merge the current PR.

2024-03-12 07:41 UTC, Prem-MysteryPro commented on Source/Tests/Tests.Runtime/Measurement Server/Session Management/Session Reservation/test_PinAndPinGroupContainingSamePin_ReserveSessions_ChannelMappingsDoesNotContainDuplicatePins.vi
Before merging this PR, I have added a `Technical Debt` so that this work is not missed. Please find the technical debt to update the palette file [here](https://dev.azure.com/ni/DevCentral/_workitems/edit/2677991).

2024-03-12 07:43 UTC, merged