Improve DC Power Example usability
ni/measurementlink-labview pull request #504
Opened 2024-04-11 18:59 UTC by nathan-murphy

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md). _(Required)_
- [x]  Automatically post PR comments with images for G code changes? _(Recommended for small changes)_

### What does this Pull Request accomplish?

Improves usability by illustrating a device reset at the end of a measurement.

### Why should this Pull Request be merged?

When our team was working with this example as a starting point, we got tripped up by needing to reconfigure the instrument and not realizing that it wasn't being handled by MeasurementLink directly. A note like this would have helped save us some development/debugging time from the start.  

### What testing has been done?

Code added is exclusively in a diagram disable structure, but we have tested that the functionality works on real hardware. Original example continues to work as normal. 

Fixes #486

2024-04-11 19:02 UTC, nathan-murphy commented
Wrong LV version was used. Will update with correct version.

2024-04-11 21:54 UTC, bkeryan commented
@nathan-murphy @dixonjoel Should the Python example be updated too? https://github.com/ni/measurementlink-python/blob/main/examples/nidcpower_source_dc_voltage/measurement.py

2024-04-12 13:19 UTC, nathan-murphy commented
@bkeryan If we started with the python measurement example it's likely that we would have run into the same issue, so yes, I think the python one should also be updated. As long as there's no dissent from @dixonjoel I'll open another issue on that repo.

2024-04-12 14:38 UTC, dixonjoel requested changes

2024-04-12 14:38 UTC, dixonjoel commented on Source/Example Measurements/NI-DCPower Source DC Voltage/NI-DCPower Measurement/subVIs/NI-DCPower Specific Logic.vi
I'll wait for the updated LV version change.

2024-04-12 14:39 UTC, nathan-murphy commented on Source/Example Measurements/NI-DCPower Source DC Voltage/NI-DCPower Measurement/subVIs/NI-DCPower Specific Logic.vi
The second commit on this PR has the VI saved for LabVIEW 2020.

2024-04-12 14:56 UTC, dixonjoel commented on Source/Example Measurements/NI-DCPower Source DC Voltage/NI-DCPower Measurement/subVIs/NI-DCPower Specific Logic.vi
I was going to ask the same thing. What are the implications or are there any drawbacks if we just always reset / abort it?

2024-04-12 15:03 UTC, nathan-murphy commented on Source/Example Measurements/NI-DCPower Source DC Voltage/NI-DCPower Measurement/subVIs/NI-DCPower Specific Logic.vi
It's not clear if Abort will reset all properties of a channel to default, so if you call different measurements with the same channel and abort between them I'm concerned that settings will bleed over from the first measurement into the second if the user doesn't explicitly set all values. 

I assume Reset takes longer than Abort, but I don't have HW available at the moment to benchmark this.

2024-04-12 16:07 UTC, dixonjoel approved these changes
Approved with suggestions.

2024-04-12 16:47 UTC, nathan-murphy commented on Source/Example Measurements/NI-DCPower Source DC Voltage/NI-DCPower Measurement/subVIs/NI-DCPower Specific Logic.vi
Point of information:
The driver example referenced in this Measurement example uses Reset. I'll stick with Reset for consistency.

2024-04-12 18:15 UTC, merged